"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { Prisma } from "@prisma/client";import { db } from "@/lib/db";
import { z } from "zod";
import { requireActiveTenant } from "@/lib/session";
import { postInterAccountTransfer } from "@/lib/transfers";
import { resolveReference } from "@/lib/reference-numbers";
import { withTransactionNotice } from "@/lib/transaction-notice";
const schema = z.object({ reference: z.string().trim().max(40).default(""),autoReference:z.string().optional(), transferDate: z.coerce.date(), description: z.string().trim().max(500), sourceAccountId: z.string().min(1), sourceCurrency: z.string().trim().length(3), sourceAmount: z.string().min(1), destinationAccountId: z.string().min(1), destinationCurrency: z.string().trim().length(3), destinationAmount: z.string().min(1) });
export async function createTransfer(formData: FormData) { const { user, active } = await requireActiveTenant(); const input = schema.parse(Object.fromEntries(formData)),reference=await resolveReference({tenantId:active.id,kind:"TRANSFER",date:input.transferDate,supplied:input.reference,auto:input.autoReference==="true"}); await postInterAccountTransfer({ actor: { tenantId: active.id, userId: user.id, firmId: user.firmId, role: user.staffRole },reference,transferDate:input.transferDate,description:input.description,sourceAccountId:input.sourceAccountId,sourceCurrency:input.sourceCurrency,sourceAmount:input.sourceAmount,destinationAccountId:input.destinationAccountId,destinationCurrency:input.destinationCurrency,destinationAmount:input.destinationAmount }); redirect(withTransactionNotice("/transfers","transfer")); }
export async function updateTransfer(formData:FormData){const{user,active}=await requireActiveTenant();if(!user.staffRole||!["SYSTEM_ADMIN","FIRM_ADMIN","ACCOUNTANT"].includes(user.staffRole))throw new Error("Your role cannot update transfers.");const input=z.object({id:z.string().min(1),reference:z.string().trim().min(1).max(40),description:z.string().trim().max(500),reason:z.string().trim().min(5).max(240)}).parse(Object.fromEntries(formData));await db.$transaction(async tx=>{const transfer=await tx.interAccountTransfer.findFirst({where:{id:input.id,tenantId:active.id}});if(!transfer)throw new Error("Transfer not found.");await tx.interAccountTransfer.update({where:{id:transfer.id},data:{reference:input.reference,description:input.description||null}});if(transfer.journalId)await tx.journal.update({where:{id:transfer.journalId},data:{reference:input.reference,description:input.description||"Inter-account transfer"}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INTER_ACCOUNT_TRANSFER_UPDATED",entityType:"InterAccountTransfer",entityId:transfer.id,previousValues:{reference:transfer.reference,description:transfer.description},newValues:{reference:input.reference,description:input.description},reason:input.reason}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});revalidatePath("/transfers");revalidatePath("/journals");redirect("/transfers")}
