import "server-only";import{Prisma}from"@prisma/client";import{db}from"./db";const zero=new Prisma.Decimal(0);
export async function inventoryQuantitySummary(tenantId:string,asOf:Date){const movements=await db.inventoryMovement.findMany({where:{tenantId,movementDate:{lte:asOf}},include:{item:true,location:true},orderBy:[{item:{sku:"asc"}},{location:{code:"asc"}}]});const rows=new Map<string,{id:string;sku:string;name:string;unit:string;quantity:Prisma.Decimal;value:Prisma.Decimal;locations:Map<string,Prisma.Decimal>}>();for(const movement of movements){const row=rows.get(movement.itemId)??{id:movement.itemId,sku:movement.item.sku,name:movement.item.name,unit:movement.item.unitName,quantity:zero,value:zero,locations:new Map<string,Prisma.Decimal>()};row.quantity=row.quantity.add(movement.quantity);row.value=row.value.add(movement.totalCost);row.locations.set(movement.location.code,(row.locations.get(movement.location.code)??zero).add(movement.quantity));rows.set(movement.itemId,row)}return[...rows.values()].map(row=>({...row,locationCount:[...row.locations.values()].filter(x=>!x.eq(0)).length,averageCost:row.quantity.eq(0)?zero:row.value.div(row.quantity)})).filter(row=>!row.quantity.eq(0)||!row.value.eq(0))}

export async function inventoryQuantityMovementSummary(tenantId:string,from:Date,to:Date){
  if(from>to)throw new Error("From date cannot be after To date.");
  const movements=await db.inventoryMovement.findMany({where:{tenantId,movementDate:{lte:to}},include:{item:true,location:true},orderBy:[{item:{sku:"asc"}},{movementDate:"asc"}]});
  const rows=new Map<string,{id:string;sku:string;name:string;unit:string;openingQuantity:Prisma.Decimal;quantityIn:Prisma.Decimal;quantityOut:Prisma.Decimal;closingQuantity:Prisma.Decimal;closingValue:Prisma.Decimal;locations:Map<string,Prisma.Decimal>}>();
  for(const movement of movements){
    const row=rows.get(movement.itemId)??{id:movement.itemId,sku:movement.item.sku,name:movement.item.name,unit:movement.item.unitName,openingQuantity:zero,quantityIn:zero,quantityOut:zero,closingQuantity:zero,closingValue:zero,locations:new Map<string,Prisma.Decimal>()};
    row.closingQuantity=row.closingQuantity.add(movement.quantity);row.closingValue=row.closingValue.add(movement.totalCost);row.locations.set(movement.location.code,(row.locations.get(movement.location.code)??zero).add(movement.quantity));
    if(movement.movementDate<from)row.openingQuantity=row.openingQuantity.add(movement.quantity);else if(movement.quantity.gt(0))row.quantityIn=row.quantityIn.add(movement.quantity);else row.quantityOut=row.quantityOut.add(movement.quantity.abs());
    rows.set(movement.itemId,row);
  }
  return[...rows.values()].map(row=>({...row,locationCount:[...row.locations.values()].filter(value=>!value.eq(0)).length,averageCost:row.closingQuantity.eq(0)?zero:row.closingValue.div(row.closingQuantity)})).filter(row=>!row.openingQuantity.eq(0)||!row.quantityIn.eq(0)||!row.quantityOut.eq(0)||!row.closingQuantity.eq(0)||!row.closingValue.eq(0));
}
export async function inventoryProfitMargin(tenantId:string,from:Date,to:Date){const[invoiceLines,movements]=await Promise.all([db.salesInvoiceLine.findMany({where:{inventoryItemId:{not:null},invoice:{tenantId,invoiceDate:{gte:from,lte:to},status:{not:"VOIDED"}}},include:{inventoryItem:true}}),db.inventoryMovement.findMany({where:{tenantId,type:{in:["SALE","SALES_RETURN"]},movementDate:{gte:from,lte:to}},include:{item:true}})]);const rows=new Map<string,{id:string;sku:string;name:string;quantity:Prisma.Decimal;revenue:Prisma.Decimal;cogs:Prisma.Decimal}>();for(const line of invoiceLines){if(!line.inventoryItem)continue;const row=rows.get(line.inventoryItemId!)??{id:line.inventoryItemId!,sku:line.inventoryItem.sku,name:line.inventoryItem.name,quantity:zero,revenue:zero,cogs:zero};row.quantity=row.quantity.add(line.quantity);row.revenue=row.revenue.add(line.lineTotal);rows.set(row.id,row)}for(const movement of movements){const row=rows.get(movement.itemId)??{id:movement.itemId,sku:movement.item.sku,name:movement.item.name,quantity:zero,revenue:zero,cogs:zero};row.cogs=row.cogs.add(movement.totalCost.abs().mul(movement.type==="SALES_RETURN"?-1:1));rows.set(row.id,row)}return[...rows.values()].map(row=>{const profit=row.revenue.sub(row.cogs);return{...row,profit,margin:row.revenue.eq(0)?zero:profit.div(row.revenue).mul(100)}}).filter(row=>!row.revenue.eq(0)||!row.cogs.eq(0))}
export async function inventoryQuantityByLocation(tenantId:string,asOf:Date){const movements=await db.inventoryMovement.findMany({where:{tenantId,movementDate:{lte:asOf}},include:{item:true,location:true},orderBy:[{location:{code:"asc"}},{item:{sku:"asc"}}]});const rows=new Map<string,{key:string;locationCode:string;location:string;branch:string;sku:string;item:string;unit:string;quantity:Prisma.Decimal;value:Prisma.Decimal}>();for(const movement of movements){const key=`${movement.locationId}:${movement.itemId}`,row=rows.get(key)??{key,locationCode:movement.location.code,location:movement.location.name,branch:movement.location.branchLabel??"—",sku:movement.item.sku,item:movement.item.name,unit:movement.item.unitName,quantity:zero,value:zero};row.quantity=row.quantity.add(movement.quantity);row.value=row.value.add(movement.totalCost);rows.set(key,row)}return[...rows.values()].filter(row=>!row.quantity.eq(0)||!row.value.eq(0))}
export async function inventoryCostingWorksheet(tenantId:string,from:Date,to:Date){const movements=await db.inventoryMovement.findMany({where:{tenantId,movementDate:{lte:to}},include:{item:true},orderBy:[{item:{sku:"asc"}},{movementDate:"asc"}]});const rows=new Map<string,{id:string;sku:string;name:string;unit:string;openingQty:Prisma.Decimal;openingValue:Prisma.Decimal;purchaseQty:Prisma.Decimal;purchaseValue:Prisma.Decimal;saleQty:Prisma.Decimal;saleCost:Prisma.Decimal;otherQty:Prisma.Decimal;otherValue:Prisma.Decimal;closingQty:Prisma.Decimal;closingValue:Prisma.Decimal}>();for(const movement of movements){const row=rows.get(movement.itemId)??{id:movement.itemId,sku:movement.item.sku,name:movement.item.name,unit:movement.item.unitName,openingQty:zero,openingValue:zero,purchaseQty:zero,purchaseValue:zero,saleQty:zero,saleCost:zero,otherQty:zero,otherValue:zero,closingQty:zero,closingValue:zero};if(movement.movementDate<from){row.openingQty=row.openingQty.add(movement.quantity);row.openingValue=row.openingValue.add(movement.totalCost)}else if(movement.type==="PURCHASE"||movement.type==="PURCHASE_RETURN"){row.purchaseQty=row.purchaseQty.add(movement.quantity);row.purchaseValue=row.purchaseValue.add(movement.totalCost)}else if(movement.type==="SALE"||movement.type==="SALES_RETURN"){row.saleQty=row.saleQty.add(movement.quantity.abs().mul(movement.type==="SALES_RETURN"?-1:1));row.saleCost=row.saleCost.add(movement.totalCost.abs().mul(movement.type==="SALES_RETURN"?-1:1))}else{row.otherQty=row.otherQty.add(movement.quantity);row.otherValue=row.otherValue.add(movement.totalCost)}row.closingQty=row.closingQty.add(movement.quantity);row.closingValue=row.closingValue.add(movement.totalCost);rows.set(row.id,row)}return[...rows.values()].map(row=>({...row,closingAverage:row.closingQty.eq(0)?zero:row.closingValue.div(row.closingQty)})).filter(row=>!row.openingQty.eq(0)||!row.purchaseQty.eq(0)||!row.saleQty.eq(0)||!row.otherQty.eq(0)||!row.closingQty.eq(0))}
