import "server-only";
import { Prisma } from "@prisma/client";
import { db } from "./db";
import { calculateFixedAssetBookValue } from "./fixed-assets";
const zero=new Prisma.Decimal(0),sum=(values:Prisma.Decimal[])=>values.reduce((total,value)=>total.add(value),zero);
export type CloseCheck={key:string;label:string;status:"PASS"|"WARNING"|"FAIL";ledger?:Prisma.Decimal;supporting?:Prisma.Decimal;difference?:Prisma.Decimal;detail:string;href:string};
export async function monthEndReview(tenantId:string,asOf:Date){
 const[journalLines,invoices,bills,movements,drafts,period,periodCount,bankAccounts,reconciliations,fixedAssets,payrollRuns,payrollSettlements,controlAccounts,tenant,inventoryBalances,fifoLayers]=await Promise.all([
  db.journalLine.findMany({where:{journal:{tenantId,accountingDate:{lte:asOf},status:{in:["POSTED","REVERSED"]}}},include:{account:true}}),
  db.salesInvoice.findMany({where:{tenantId,invoiceDate:{lte:asOf},status:{not:"VOIDED"}},include:{allocations:{include:{receipt:true}},creditNotes:true}}),
  db.supplierBill.findMany({where:{tenantId,billDate:{lte:asOf},status:{not:"VOIDED"}},include:{allocations:{include:{payment:true}},creditNotes:true}}),
  db.inventoryMovement.findMany({where:{tenantId,movementDate:{lte:asOf}},include:{item:true}}),
  db.journal.count({where:{tenantId,accountingDate:{lte:asOf},status:{in:["DRAFT","IN_REVIEW","APPROVED"]}}}),
  db.accountingPeriod.findFirst({where:{tenantId,startsOn:{lte:asOf},endsOn:{gte:asOf}},orderBy:{startsOn:"desc"}}),
  db.accountingPeriod.count({where:{tenantId,startsOn:{lte:asOf},endsOn:{gte:asOf}}}),
  db.account.findMany({where:{tenantId,isActive:true,type:"ASSET",reportingClassification:"Cash and cash equivalents"},select:{id:true}}),
  db.bankReconciliation.findMany({where:{tenantId,status:"RECONCILED",statementEnd:{lte:asOf}},orderBy:{statementEnd:"desc"}}),
  db.fixedAsset.findMany({where:{tenantId,status:"ACTIVE",acquiredOn:{lte:asOf}},include:{depreciationEntries:{where:{depreciationDate:{lte:asOf}}}}}),
  db.payrollRun.findMany({where:{tenantId,payDate:{lte:asOf},status:{in:["POSTED","LOCKED"]}},include:{entries:true}}),
  db.payrollSettlement.findMany({where:{tenantId,paymentDate:{lte:asOf}}}),
  db.account.findMany({where:{tenantId,isActive:true,code:{in:["1200","2000","2210"]}},select:{code:true}}),
  db.tenant.findUniqueOrThrow({where:{id:tenantId},select:{inventoryCostingMethod:true}}),
  db.inventoryBalance.findMany({where:{item:{tenantId}},select:{itemId:true,locationId:true,quantity:true,inventoryValue:true}}),
  db.inventoryCostLayer.findMany({where:{tenantId,remainingQuantity:{gt:zero}},select:{itemId:true,locationId:true,remainingQuantity:true,unitCost:true}})
 ]);
 const debit=sum(journalLines.map(line=>line.debit)),credit=sum(journalLines.map(line=>line.credit)),ledgerAr=sum(journalLines.filter(line=>line.account.code==="1200").map(line=>line.debit.sub(line.credit))),ledgerAp=sum(journalLines.filter(line=>["2000","2100"].includes(line.account.code)).map(line=>line.credit.sub(line.debit)));
 const subledgerAr=sum(invoices.map(invoice=>invoice.baseTotal.sub(sum(invoice.allocations.filter(a=>a.receipt.receiptDate<=asOf).map(a=>a.carryingBaseAmount))).sub(sum(invoice.creditNotes.filter(note=>note.creditDate<=asOf).map(note=>note.baseTotal))))),subledgerAp=sum(bills.map(bill=>bill.baseTotal.sub(sum(bill.allocations.filter(a=>a.payment.paymentDate<=asOf).map(a=>a.carryingBaseAmount))).sub(sum(bill.creditNotes.filter(note=>note.creditDate<=asOf).map(note=>note.baseTotal)))));
 const inventoryAccountIds=[...new Set(movements.map(m=>m.item.inventoryAccountId))],ledgerInventory=sum(journalLines.filter(line=>inventoryAccountIds.includes(line.accountId)).map(line=>line.debit.sub(line.credit))),movementInventory=sum(movements.map(movement=>movement.totalCost));
 const comparison=(key:string,label:string,ledger:Prisma.Decimal,supporting:Prisma.Decimal,href:string):CloseCheck=>{const difference=ledger.sub(supporting),pass=difference.abs().lt(new Prisma.Decimal("0.01"));return{key,label,status:pass?"PASS":"FAIL",ledger,supporting,difference,detail:pass?"Ledger agrees with the supporting register.":"Investigate and correct the difference before closing the period.",href}};
 const reconciledAccounts=new Set(reconciliations.map(item=>item.accountId)),unreconciled=bankAccounts.filter(account=>!reconciledAccounts.has(account.id)).length;
 const depreciationDue=fixedAssets.reduce((total,asset)=>{const schedule=calculateFixedAssetBookValue({originalCost:Number(asset.originalCost),residualValue:Number(asset.residualValue),openingAccumulatedDepreciation:Number(asset.openingAccumulatedDepreciation),usefulLifeMonths:asset.usefulLifeMonths,depreciationStartsOn:asset.depreciationStartsOn,asOf}),posted=asset.depreciationEntries.reduce((sum,entry)=>sum+Number(entry.amount),0);return total+Math.max(0,schedule.accumulatedDepreciation-Number(asset.openingAccumulatedDepreciation)-posted)},0);
 const quantities=new Map<string,Prisma.Decimal>();for(const movement of movements){const key=`${movement.itemId}:${movement.locationId}`,current=quantities.get(key)??zero;quantities.set(key,current.add(movement.quantity))}const negativeInventoryCount=[...quantities.values()].filter(quantity=>quantity.lt(0)).length;
 const fifoByKey=new Map<string,{quantity:Prisma.Decimal;value:Prisma.Decimal}>();for(const layer of fifoLayers){const key=`${layer.itemId}:${layer.locationId}`,current=fifoByKey.get(key)??{quantity:zero,value:zero};current.quantity=current.quantity.add(layer.remainingQuantity);current.value=current.value.add(layer.remainingQuantity.mul(layer.unitCost));fifoByKey.set(key,current)}const fifoDifferences=tenant.inventoryCostingMethod==="FIFO"?inventoryBalances.filter(balance=>{const layers=fifoByKey.get(`${balance.itemId}:${balance.locationId}`)??{quantity:zero,value:zero};return!balance.quantity.eq(layers.quantity)||balance.inventoryValue.sub(layers.value).abs().gte(new Prisma.Decimal("0.01"))}):[];
 const payrollLedger=sum(journalLines.filter(line=>line.account.code==="2210").map(line=>line.credit.sub(line.debit))),payrollSupporting=sum(payrollRuns.flatMap(run=>run.entries.map(entry=>entry.netPay))).sub(sum(payrollSettlements.map(settlement=>settlement.amount)));
 const openProfit=sum(journalLines.filter(line=>line.account.type==="REVENUE").map(line=>line.credit.sub(line.debit))).sub(sum(journalLines.filter(line=>line.account.type==="EXPENSE").map(line=>line.debit.sub(line.credit))));
 const currentEarningsAccount=sum(journalLines.filter(line=>line.account.type==="EQUITY"&&(line.account.code==="3200"||line.account.name.trim().toLowerCase()==="current-year earnings")).map(line=>line.credit.sub(line.debit))),duplicateCurrentEarnings=!openProfit.eq(0)&&!currentEarningsAccount.eq(0);
 const requiredControls=["1200","2000",...(payrollRuns.length?["2210"]:[])],configuredControls=new Set(controlAccounts.map(account=>account.code)),missingControls=requiredControls.filter(code=>!configuredControls.has(code));
 const checks:CloseCheck[]=[
  {key:"ledger",label:"General ledger balance",status:debit.eq(credit)?"PASS":"FAIL",ledger:debit,supporting:credit,difference:debit.sub(credit),detail:debit.eq(credit)?"Posted debits equal posted credits.":"The posted ledger is out of balance.",href:"/reports/trial-balance"},
  comparison("receivables","Trade receivables control",ledgerAr,subledgerAr,"/reports/receivables"),
  comparison("payables","Trade payables control",ledgerAp,subledgerAp,"/reports/payables"),
  comparison("inventory","Inventory valuation control",ledgerInventory,movementInventory,"/reports/inventory-valuation"),
  comparison("payroll","Payroll net-pay control",payrollLedger,payrollSupporting,"/reports/payroll-summary"),
  {key:"negative-inventory",label:"Negative inventory",status:negativeInventoryCount?"FAIL":"PASS",detail:negativeInventoryCount?`${negativeInventoryCount} item-location balance${negativeInventoryCount===1?" is":"s are"} below zero. Correct purchase timing, counts, or item allocations before close.`:"No item-location balances are below zero.",href:"/reports/inventory-quantity-by-location"},
  {key:"fifo-layers",label:"FIFO cost-layer integrity",status:fifoDifferences.length?"FAIL":"PASS",detail:tenant.inventoryCostingMethod!=="FIFO"?"Not applicable; this company uses weighted-average costing.":fifoDifferences.length?`${fifoDifferences.length} item-location FIFO layer balance${fifoDifferences.length===1?" does":"s do"} not agree with the inventory register.`:"FIFO quantities and carrying values agree with the inventory register.",href:"/reports/inventory-costing-worksheet"},
  {key:"controls",label:"Required control accounts",status:missingControls.length?"FAIL":"PASS",detail:missingControls.length?`Active control account${missingControls.length===1?"":"s"} ${missingControls.join(", ")} ${missingControls.length===1?"is":"are"} missing.`:"Required receivable, payable, and applicable payroll controls are active.",href:"/accounts"},
  {key:"drafts",label:"Unposted journal workflow",status:drafts?"WARNING":"PASS",detail:drafts?`${drafts} journal${drafts===1?" is":"s are"} not posted through the review date.`:"No unposted journals through the review date.",href:"/journals"},
  {key:"bank",label:"Bank reconciliation coverage",status:unreconciled?"WARNING":"PASS",detail:unreconciled?`${unreconciled} active cash or bank account${unreconciled===1?" has":"s have"} no completed reconciliation through this date.`:"All active cash and bank accounts have a completed reconciliation.",href:"/reconciliations"},
  {key:"depreciation",label:"Fixed-asset depreciation",status:depreciationDue>0.005?"WARNING":"PASS",detail:depreciationDue>0.005?`${depreciationDue.toLocaleString("en-BN",{minimumFractionDigits:2,maximumFractionDigits:2})} of book depreciation remains unposted through the review date.`:"Fixed-asset depreciation is posted through the review date.",href:`/fixed-assets/depreciation?asOf=${asOf.toISOString().slice(0,10)}`},
  {key:"current-earnings",label:"Current earnings presentation",status:duplicateCurrentEarnings?"FAIL":"PASS",ledger:currentEarningsAccount,supporting:openProfit,difference:currentEarningsAccount.sub(openProfit),detail:duplicateCurrentEarnings?"The Current-year earnings equity account and revenue/expense accounts both contain balances. Review year-end closing entries to prevent earnings being presented twice.":"No duplicate current-earnings presentation was detected.",href:`/reports/balance-sheet?asOf=${asOf.toISOString().slice(0,10)}`},
  {key:"period",label:"Accounting period",status:periodCount>1?"FAIL":period?period.status==="OPEN"?"PASS":"WARNING":"FAIL",detail:periodCount>1?`${periodCount} accounting periods overlap the review date.`:period?`${period.name} is ${period.status.toLowerCase()}.`:"No accounting period contains the review date.",href:"/settings/periods"}
 ];
 return{checks,ready:checks.every(check=>check.status==="PASS"),period};
}
