"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import type { RetailImportState } from "@/components/retail-sales-import-form";
import { db } from "@/lib/db";
import { postDailyCashRegister } from "@/lib/daily-cash-sales";
import { requireActiveTenant } from "@/lib/session";
import { resolveReference } from "@/lib/reference-numbers";
import { withTransactionNotice } from "@/lib/transaction-notice";
const schema=z.object({reference:z.string().trim().max(40).default(""),autoReference:z.string().optional(),registerDate:z.coerce.date(),cashAccountId:z.string().min(1),branchLabel:z.string().trim().max(80),registerLabel:z.string().trim().max(80),openingFloat:z.string(),actualClosingCash:z.string(),cashAmount:z.string(),cardAmount:z.string(),cardAccountId:z.string(),bankAmount:z.string(),bankAccountId:z.string(),otherAmount:z.string(),otherAccountId:z.string(),skuColumn:z.string().min(1),locationColumn:z.string().min(1),quantityColumn:z.string().min(1),unitPriceColumn:z.string(),totalAmountColumn:z.string(),descriptionColumn:z.string()});
function fields(row:string){const values:string[]=[];let value="",quoted=false;for(let i=0;i<row.length;i++){const char=row[i];if(char==='"'&&quoted&&row[i+1]==='"'){value+='"';i++}else if(char==='"')quoted=!quoted;else if(char===","&&!quoted){values.push(value.trim());value=""}else value+=char}values.push(value.trim());return values}
export async function importRetailSales(_:RetailImportState,formData:FormData):Promise<RetailImportState>{
  try{
    const{user,active}=await requireActiveTenant(),input=schema.parse(Object.fromEntries(formData)),file=formData.get("salesFile");
    input.reference=await resolveReference({tenantId:active.id,kind:"DAILY_SALE",date:input.registerDate,supplied:input.reference,auto:input.autoReference==="true"});
    const period=await db.accountingPeriod.findFirst({where:{tenantId:active.id,status:"OPEN",startsOn:{lte:input.registerDate},endsOn:{gte:input.registerDate}},orderBy:{startsOn:"desc"}});
    if(!period)throw new Error("The register date is not inside an open accounting period. Open that month under Administration → Accounting periods, or choose another date.");
    if(!(file instanceof File)||file.size===0)throw new Error("Select a CSV sales summary file.");if(file.size>2_000_000)throw new Error("The sales summary cannot exceed 2 MB.");
    const rows=(await file.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(row=>row.trim()),headers=fields(rows[0]),index=(name:string)=>headers.indexOf(name),skuIndex=index(input.skuColumn),locationIndex=index(input.locationColumn),quantityIndex=index(input.quantityColumn),priceIndex=index(input.unitPriceColumn),totalIndex=index(input.totalAmountColumn),descriptionIndex=index(input.descriptionColumn);
    if([skuIndex,locationIndex,quantityIndex].some(x=>x<0))throw new Error("One or more selected CSV columns could not be found.");if(priceIndex<0&&totalIndex<0)throw new Error("Map either a Unit price column or a Total sales amount column.");if(rows.length<2||rows.length>1001)throw new Error("The CSV must contain between 1 and 1,000 item summary rows.");
    const parsed=rows.slice(1).map((row,i)=>{const values=fields(row),sku=values[skuIndex]?.trim(),location=values[locationIndex]?.trim(),quantity=values[quantityIndex]?.trim(),rawPrice=priceIndex>=0?values[priceIndex]?.trim():"",total=totalIndex>=0?values[totalIndex]?.trim():"",qty=Number(quantity),totalValue=Number(total),unitPrice=rawPrice||((Number.isFinite(qty)&&qty>0&&Number.isFinite(totalValue))?(totalValue/qty).toFixed(6):"");if(!sku||!location||!quantity||!unitPrice)throw new Error(`CSV row ${i+2} is incomplete.`);if(!Number.isFinite(qty)||qty<=0||!Number.isFinite(Number(unitPrice))||Number(unitPrice)<0)throw new Error(`CSV row ${i+2} has an invalid quantity or price.`);return{sku,location,quantity,unitPrice,description:descriptionIndex>=0?values[descriptionIndex]?.trim():""}}),skus=[...new Set(parsed.map(x=>x.sku))],locationCodes=[...new Set(parsed.map(x=>x.location))];
    const[items,locations]=await Promise.all([db.inventoryItem.findMany({where:{tenantId:active.id,sku:{in:skus},isActive:true}}),db.inventoryLocation.findMany({where:{tenantId:active.id,code:{in:locationCodes},isActive:true}})]),itemMap=new Map(items.map(x=>[x.sku,x])),locationMap=new Map(locations.map(x=>[x.code,x]));
    const lines=parsed.map((row,i)=>{const item=itemMap.get(row.sku),location=locationMap.get(row.location);if(!item)throw new Error(`CSV row ${i+2}: SKU ${row.sku} was not found or is inactive.`);if(!location)throw new Error(`CSV row ${i+2}: location ${row.location} was not found or is inactive.`);return{description:row.description||item.name,accountId:item.revenueAccountId,inventoryItemId:item.id,inventoryLocationId:location.id,quantity:row.quantity,unitPrice:row.unitPrice}}),tenders=[]as{type:"CASH"|"CARD"|"BANK_TRANSFER"|"OTHER";accountId:string;amount:string;reference:string}[];
    const add=(type:"CASH"|"CARD"|"BANK_TRANSFER"|"OTHER",amount:string,accountId:string)=>{if(Number(amount)>0){if(!accountId)throw new Error(`Select a deposit account for ${type.replaceAll("_"," ").toLowerCase()} tenders.`);tenders.push({type,amount,accountId,reference:input.reference})}};
    add("CASH",input.cashAmount,input.cashAccountId);add("CARD",input.cardAmount,input.cardAccountId);add("BANK_TRANSFER",input.bankAmount,input.bankAccountId);add("OTHER",input.otherAmount,input.otherAccountId);
    await postDailyCashRegister({actor:{tenantId:active.id,userId:user.id,firmId:user.firmId,role:user.staffRole},periodId:period.id,cashAccountId:input.cashAccountId,reference:input.reference,registerDate:input.registerDate,branchLabel:input.branchLabel,registerLabel:input.registerLabel,openingFloat:input.openingFloat,actualClosingCash:input.actualClosingCash,lines,tenders});
  }catch(error){return{error:error instanceof Error?error.message:"The retail sales summary could not be imported."}}
  redirect(withTransactionNotice("/cash-sales", "cash-sale"));
}
