"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";
function authorize(role:string|null){if(!role||!["SYSTEM_ADMIN","FIRM_ADMIN","ACCOUNTANT"].includes(role))throw new Error("Your role cannot manage inventory setup.")}
const itemSchema=z.object({sku:z.string().trim().min(1).max(40),name:z.string().trim().min(2).max(120),description:z.string().trim().max(500),unitName:z.string().trim().min(1).max(20),inventoryAccountId:z.string().min(1),revenueAccountId:z.string().min(1),cogsAccountId:z.string().min(1)});
const locationSchema=z.object({code:z.string().trim().min(1).max(30),name:z.string().trim().min(2).max(100),branchLabel:z.string().trim().max(100)});
async function validateAccounts(tenantId:string,data:z.infer<typeof itemSchema>){const accounts=await db.account.findMany({where:{tenantId,id:{in:[data.inventoryAccountId,data.revenueAccountId,data.cogsAccountId]},isActive:true}});if(accounts.find(a=>a.id===data.inventoryAccountId)?.type!=="ASSET"||accounts.find(a=>a.id===data.revenueAccountId)?.type!=="REVENUE"||accounts.find(a=>a.id===data.cogsAccountId)?.type!=="EXPENSE")throw new Error("Inventory, revenue, and cost-of-sales accounts must have the correct account types.")}
export async function createInventoryItem(formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const data=itemSchema.parse(Object.fromEntries(formData));await validateAccounts(active.id,data);await db.$transaction(async tx=>{const item=await tx.inventoryItem.create({data:{tenantId:active.id,...data,description:data.description||null}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_ITEM_CREATED",entityType:"InventoryItem",entityId:item.id,newValues:{sku:data.sku,name:data.name,unitName:data.unitName}}})});redirect("/inventory")}
export async function createQuickInventoryItem(input:z.infer<typeof itemSchema>){
 const{user,active}=await requireActiveTenant();authorize(user.staffRole);const data=itemSchema.parse(input);await validateAccounts(active.id,data);
 const duplicate=await db.inventoryItem.findFirst({where:{tenantId:active.id,OR:[{sku:{equals:data.sku,mode:"insensitive"}},{name:{equals:data.name,mode:"insensitive"}}]}});
 if(duplicate)throw new Error(duplicate.sku.toLowerCase()===data.sku.toLowerCase()?"This SKU already exists.":"An inventory item with this name already exists.");
 const item=await db.$transaction(async tx=>{const created=await tx.inventoryItem.create({data:{tenantId:active.id,...data,description:data.description||null}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_ITEM_CREATED",entityType:"InventoryItem",entityId:created.id,newValues:{sku:data.sku,name:data.name,unitName:data.unitName,source:"QUICK_REGISTRATION"}}});return created});
 revalidatePath("/inventory");return{id:item.id,sku:item.sku,name:item.name,revenueAccountId:item.revenueAccountId,inventoryAccountId:item.inventoryAccountId,cogsAccountId:item.cogsAccountId};
}
export async function createInventoryLocation(formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const data=locationSchema.parse(Object.fromEntries(formData));await db.$transaction(async tx=>{const location=await tx.inventoryLocation.create({data:{tenantId:active.id,code:data.code,name:data.name,branchLabel:data.branchLabel||null}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_LOCATION_CREATED",entityType:"InventoryLocation",entityId:location.id,newValues:data}})});revalidatePath("/inventory");redirect("/inventory")}
export async function updateInventoryItem(id:string,formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const data=itemSchema.extend({isActive:z.string().optional()}).parse(Object.fromEntries(formData));await validateAccounts(active.id,data);const item=await db.inventoryItem.findFirst({where:{id,tenantId:active.id}});if(!item)throw new Error("Inventory item not found.");const duplicate=await db.inventoryItem.findFirst({where:{tenantId:active.id,id:{not:id},sku:{equals:data.sku,mode:"insensitive"}}});if(duplicate)redirect(`/inventory/items/${id}/edit?error=${encodeURIComponent("This SKU already exists.")}`);await db.$transaction(async tx=>{await tx.inventoryItem.update({where:{id},data:{sku:data.sku,name:data.name,description:data.description||null,unitName:data.unitName,inventoryAccountId:data.inventoryAccountId,revenueAccountId:data.revenueAccountId,cogsAccountId:data.cogsAccountId,isActive:data.isActive==="on"}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_ITEM_UPDATED",entityType:"InventoryItem",entityId:id,previousValues:{sku:item.sku,name:item.name},newValues:{sku:data.sku,name:data.name}}})});revalidatePath("/inventory");redirect("/inventory")}
export async function deleteInventoryItem(id:string,formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const reason=z.string().trim().min(5).max(240).parse(formData.get("reason"));z.literal("DELETE").parse(formData.get("confirmation"));const item=await db.inventoryItem.findFirst({where:{id,tenantId:active.id},include:{_count:{select:{movements:true,operations:true,salesInvoiceLines:true,supplierBillLines:true}}}});if(!item)throw new Error("Inventory item not found.");const linked=item._count.movements+item._count.operations+item._count.salesInvoiceLines+item._count.supplierBillLines;if(linked)redirect(`/inventory/items/${id}/edit?error=${encodeURIComponent("This item has stock or invoice history and cannot be deleted. Mark it inactive instead.")}`);await db.$transaction(async tx=>{await tx.inventoryBalance.deleteMany({where:{itemId:id}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_ITEM_DELETED",entityType:"InventoryItem",entityId:id,previousValues:{sku:item.sku,name:item.name},reason}});await tx.inventoryItem.delete({where:{id}})});redirect("/inventory")}
export async function updateInventoryLocation(id:string,formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const data=locationSchema.extend({isActive:z.string().optional()}).parse(Object.fromEntries(formData)),location=await db.inventoryLocation.findFirst({where:{id,tenantId:active.id}});if(!location)throw new Error("Stock location not found.");const duplicate=await db.inventoryLocation.findFirst({where:{tenantId:active.id,id:{not:id},code:{equals:data.code,mode:"insensitive"}}});if(duplicate)redirect(`/inventory/locations/${id}/edit?error=${encodeURIComponent("This location code already exists.")}`);await db.$transaction(async tx=>{await tx.inventoryLocation.update({where:{id},data:{code:data.code,name:data.name,branchLabel:data.branchLabel||null,isActive:data.isActive==="on"}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_LOCATION_UPDATED",entityType:"InventoryLocation",entityId:id,previousValues:{code:location.code,name:location.name},newValues:data}})});revalidatePath("/inventory");redirect("/inventory")}
export async function deleteInventoryLocation(id:string,formData:FormData){const{user,active}=await requireActiveTenant();authorize(user.staffRole);const reason=z.string().trim().min(5).max(240).parse(formData.get("reason"));z.literal("DELETE").parse(formData.get("confirmation"));const location=await db.inventoryLocation.findFirst({where:{id,tenantId:active.id},include:{_count:{select:{movements:true,salesInvoiceLines:true,supplierBillLines:true,sourceOperations:true,destinationOperations:true}}}});if(!location)throw new Error("Stock location not found.");const linked=location._count.movements+location._count.salesInvoiceLines+location._count.supplierBillLines+location._count.sourceOperations+location._count.destinationOperations;if(linked)redirect(`/inventory/locations/${id}/edit?error=${encodeURIComponent("This location has stock or transaction history and cannot be deleted. Mark it inactive instead.")}`);await db.$transaction(async tx=>{await tx.inventoryBalance.deleteMany({where:{locationId:id}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"INVENTORY_LOCATION_DELETED",entityType:"InventoryLocation",entityId:id,previousValues:{code:location.code,name:location.name},reason}});await tx.inventoryLocation.delete({where:{id}})});redirect("/inventory")}
