import Link from "next/link";
import { MapPin, PackageOpen, Plus } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { SetupRecordActions } from "@/components/setup-record-actions";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";
import { updateInventoryCostingMethod } from "./costing-actions";
export const dynamic="force-dynamic";
export default async function Page(){
  const{user,tenants,active}=await requireActiveTenant();
  const[items,locations]=await Promise.all([db.inventoryItem.findMany({where:{tenantId:active.id},include:{inventoryAccount:true,revenueAccount:true,cogsAccount:true,balances:true},orderBy:{sku:"asc"}}),db.inventoryLocation.findMany({where:{tenantId:active.id},include:{balances:true},orderBy:{code:"asc"}})]);
  return <AppShell user={{displayName:user.displayName,email:user.email,role:user.staffRole?.replaceAll("_"," ")??"STAFF",firmName:user.firm.name}} tenants={tenants} activeTenant={active} pageTitle="Inventory" pageDescription="Items, stock locations, quantities, and valuation"><main className="module-page">
    <header className="module-header"><div><p className="eyebrow">{active.legalName.toUpperCase()}</p><h2>Inventory register</h2><p>Perpetual inventory foundation using per-location quantity and value balances.</p></div><div className="form-actions"><Link href="/inventory/opening" className="button-secondary"><PackageOpen size={16}/>Opening inventory</Link><Link href="/inventory/locations/new" className="button-secondary"><MapPin size={16}/>New location</Link><Link href="/inventory/items/new" className="button-primary"><Plus size={16}/>New item</Link></div></header>
    <section className="surface-card compact-form-body"><div className="card-header"><div><h3>Inventory costing method</h3><p>FIFO issues the oldest available cost layers first. A conversion from weighted average is prospective from the current carrying value and is recorded in the audit trail.</p></div></div><form action={updateInventoryCostingMethod} className="form-actions"><label>Costing method<select name="method" defaultValue={active.inventoryCostingMethod}><option value="WEIGHTED_AVERAGE">Weighted average</option><option value="FIFO">FIFO (first in, first out)</option></select></label><button className="button-secondary">Save costing method</button></form></section>
    <section className="surface-card table-card"><div className="section-heading"><h2>Inventory items</h2></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Unit</th><th>Inventory</th><th>Revenue</th><th>COGS</th><th className="numeric">Quantity</th><th className="numeric">Value</th><th aria-label="Options"></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.sku}</strong></td><td>{item.name}</td><td>{item.unitName}</td><td>{item.inventoryAccount.code}</td><td>{item.revenueAccount.code}</td><td>{item.cogsAccount.code}</td><td className="numeric">{item.balances.reduce((s,b)=>s+Number(b.quantity),0).toFixed(4)}</td><td className="numeric">{active.defaultCurrency} {item.balances.reduce((s,b)=>s+Number(b.inventoryValue),0).toFixed(2)}</td><td><SetupRecordActions editHref={`/inventory/items/${item.id}/edit`}/></td></tr>)}{!items.length&&<tr><td colSpan={9}>No inventory items configured.</td></tr>}</tbody></table></div></section>
    <section className="surface-card table-card"><div className="section-heading"><h2>Stock locations</h2></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Location</th><th>Branch</th><th>Status</th><th className="numeric">Item balances</th><th aria-label="Options"></th></tr></thead><tbody>{locations.map(location=><tr key={location.id}><td><strong>{location.code}</strong></td><td>{location.name}</td><td>{location.branchLabel||"—"}</td><td><span className={`status-badge ${location.isActive?"active":"inactive"}`}>{location.isActive?"ACTIVE":"INACTIVE"}</span></td><td className="numeric">{location.balances.length}</td><td><SetupRecordActions editHref={`/inventory/locations/${location.id}/edit`}/></td></tr>)}{!locations.length&&<tr><td colSpan={6}>No stock locations configured.</td></tr>}</tbody></table></div></section>
  </main></AppShell>;
}
