import Link from "next/link";
import { Download } from "lucide-react";
import { Prisma } from "@prisma/client";
import { AppShell } from "@/components/app-shell";
import { ProfitLossStatementView } from "@/components/profit-loss-statement";
import { calculateBalanceSheet } from "@/lib/financial-statements";
import { buildBalanceSheetPresentation, type BalanceSheetDisplayRow } from "@/lib/balance-sheet-report";
import { calculateProfitLoss } from "@/lib/profit-loss";
import { agedPayables, agedReceivables, inventoryValuation, ledgerBalances } from "@/lib/reports";
import { requireActiveTenant } from "@/lib/session";
import { publishReport } from "../publish-actions";
import { formatCurrencyAmount } from "@/lib/currency";

export const dynamic = "force-dynamic";
const zero = new Prisma.Decimal(0);
const money = formatCurrencyAmount;
const date = (value: string | undefined, fallback: Date) => { if (!value) return fallback; const parsed = new Date(`${value}T00:00:00`); return Number.isNaN(parsed.getTime()) ? fallback : parsed; };

export default async function Page({ params, searchParams }: { params: Promise<{ type: string }>; searchParams: Promise<{ from?: string; to?: string; asOf?: string }> }) {
  const { type } = await params, query = await searchParams, { user, tenants, active } = await requireActiveTenant();
  const now = new Date(), asOf = date(query.asOf ?? query.to, now), from = date(query.from, new Date(now.getFullYear(), 0, 1));
  const names: Record<string, string> = { "trial-balance": "Trial Balance", "profit-loss": "Profit & Loss", "revenue-statement": "Revenue Statement", "balance-sheet": "Balance Sheet", receivables: "Aged Receivables", payables: "Aged Payables", inventory: "Inventory Valuation" };
  const title = names[type], shellUser = { displayName: user.displayName, email: user.email, role: user.staffRole?.replaceAll("_", " ") ?? "STAFF", firmName: user.firm.name };
  if (!title) return <AppShell user={shellUser} tenants={tenants} activeTenant={active} pageTitle="Report not found" pageDescription="Unknown report"><p>Report not found.</p></AppShell>;
  let body: React.ReactNode;
  if (type === "trial-balance") {
    const rows = await ledgerBalances(active.id, undefined, asOf), debits = rows.reduce((s, r) => s.add(r.balance.gt(0) ? r.balance : zero), zero), credits = rows.reduce((s, r) => s.add(r.balance.lt(0) ? r.balance.abs() : zero), zero);
    body = <><Summary items={[["Total debits", money(active.defaultCurrency, debits)], ["Total credits", money(active.defaultCurrency, credits)], ["Difference", money(active.defaultCurrency, debits.sub(credits))], ["Status", debits.eq(credits) ? "BALANCED" : "OUT OF BALANCE"]]} /><ReportTable heads={["Code", "Account", "Type", "Debit", "Credit"]} rows={rows.map(r => [r.code, r.name, r.type, money(active.defaultCurrency, r.balance.gt(0) ? r.balance : zero), money(active.defaultCurrency, r.balance.lt(0) ? r.balance.abs() : zero)])} /></>;
  } else if (type === "profit-loss" || type === "revenue-statement") {
    const statement = calculateProfitLoss(await ledgerBalances(active.id, from, asOf, { excludeYearEndClosing: true }));
    body = <><Summary items={[["Net revenue", money(active.defaultCurrency, statement.netRevenue)], ["Gross profit", money(active.defaultCurrency, statement.grossProfit)], ["Operating income", money(active.defaultCurrency, statement.operatingIncome)], ["Net income", money(active.defaultCurrency, statement.netIncome)]]} /><ProfitLossStatementView statement={statement} currency={active.defaultCurrency}/></>;
  } else if (type === "balance-sheet") {
    const s = calculateBalanceSheet(await ledgerBalances(active.id, undefined, asOf));
    const view = buildBalanceSheetPresentation(s);
    const display = (rows: BalanceSheetDisplayRow[]) => rows.map(r => [r.code, r.name, money(active.defaultCurrency, r.amount)]);
    body = <><Summary items={[["Total assets", money(active.defaultCurrency, s.totalAssets)], ["Liabilities + equity", money(active.defaultCurrency, s.totalLiabilitiesAndEquity)], ["Net Income / (Loss)", money(active.defaultCurrency, s.currentEarnings)], ["Balance check", s.difference.eq(0) ? "BALANCED" : money(active.defaultCurrency, s.difference)]]} /><section className="surface-card balance-sheet-statement">{view.currentAssets.length > 0 && <Statement title="Current Assets" rows={display(view.currentAssets)} totalLabel="Total Current Assets" total={money(active.defaultCurrency, view.totalCurrentAssets)} />}{view.fixedAssets.length > 0 && <Statement title="Non-Current Assets" rows={display(view.fixedAssets)} totalLabel="Net Fixed Assets" total={money(active.defaultCurrency, view.netFixedAssets)} />}{view.otherNonCurrentAssets.length > 0 && <Statement title="Other Non-Current Assets" rows={display(view.otherNonCurrentAssets)} totalLabel="Other Non-Current Assets" total={money(active.defaultCurrency, view.totalNonCurrentAssets.sub(view.netFixedAssets))} />}{view.otherNonCurrentAssets.length > 0 && <StandaloneTotal label="Total Non-Current Assets" value={money(active.defaultCurrency, view.totalNonCurrentAssets)} />}<StandaloneTotal label="Total Assets" value={money(active.defaultCurrency, s.totalAssets)} />{view.currentLiabilities.length > 0 && <Statement title="Current Liabilities" rows={display(view.currentLiabilities)} totalLabel="Total Current Liabilities" total={money(active.defaultCurrency, view.totalCurrentLiabilities)} />}{view.nonCurrentLiabilities.length > 0 && <Statement title="Non-Current Liabilities" rows={display(view.nonCurrentLiabilities)} totalLabel="Total Non-Current Liabilities" total={money(active.defaultCurrency, view.totalNonCurrentLiabilities)} />}<StandaloneTotal label="Total Liabilities" value={money(active.defaultCurrency, s.totalLiabilities)} /><Statement title="Equity" rows={[...display(view.equity), ...(!s.currentEarnings.eq(0) ? [["—", "Net Income / (Loss)", money(active.defaultCurrency, s.currentEarnings)]] : [])]} totalLabel="Total Equity" total={money(active.defaultCurrency, s.totalEquity)} /><StandaloneTotal label="Total Liabilities & Equity" value={money(active.defaultCurrency, s.totalLiabilitiesAndEquity)} /><div className={`statement-check ${s.difference.eq(0) ? "is-balanced" : ""}`}>Assets = Liabilities + Equity · {s.difference.eq(0) ? "Balanced" : `Difference ${money(active.defaultCurrency, s.difference)}`}</div></section></>;
  } else if (type === "receivables" || type === "payables") {
    const rows = type === "receivables" ? await agedReceivables(active.id, asOf) : await agedPayables(active.id, asOf), total = rows.reduce((s, r) => s.add(r.outstanding), zero);
    body = <><Summary items={[["Total outstanding", money(active.defaultCurrency, total)], ...["CURRENT", "1–30", "31–60"].map(bucket => [bucket, money(active.defaultCurrency, rows.filter(r => r.bucket === bucket).reduce((s, r) => s.add(r.outstanding), zero))])]} /><ReportTable heads={["Reference", type === "receivables" ? "Customer" : "Supplier", "Document date", "Due date", "Age", "Outstanding"]} rows={rows.map(r => [r.reference, r.party, r.date.toLocaleDateString("en-BN"), r.due.toLocaleDateString("en-BN"), r.bucket, money(active.defaultCurrency, r.outstanding)])} /></>;
  } else {
    const rows = await inventoryValuation(active.id, asOf), value = rows.reduce((s, r) => s.add(r.value), zero);
    body = <><Summary items={[["Inventory value", money(active.defaultCurrency, value)], ["Item/location balances", String(rows.length)], ["As of", asOf.toLocaleDateString("en-BN")], ["Basis", "WEIGHTED AVERAGE"]]} /><ReportTable heads={["SKU", "Item", "Location", "Unit", "Quantity", "Value"]} rows={rows.map(r => [r.sku, r.item, r.location, r.unit, Number(r.quantity).toFixed(4), money(active.defaultCurrency, r.value)])} /></>;
  }
  const isProfitLoss = type === "profit-loss" || type === "revenue-statement";
  const pdfQuery = isProfitLoss ? `from=${from.toISOString().slice(0, 10)}&to=${asOf.toISOString().slice(0, 10)}` : `asOf=${asOf.toISOString().slice(0, 10)}`;
  return <AppShell user={shellUser} tenants={tenants} activeTenant={active} pageTitle={title} pageDescription="Live report generated from posted accounting data"><main className="module-page"><div className="detail-toolbar"><Link href="/reports" className="back-link">← Report library</Link></div><header className="module-header"><div><p className="eyebrow">{active.legalName.toUpperCase()}</p><h2>{title}</h2><p>Generated {new Date().toLocaleString("en-BN")}</p></div><div className="report-actions"><form className="report-filter">{isProfitLoss && <label>From<input name="from" type="date" defaultValue={from.toISOString().slice(0, 10)} /></label>}<label>{isProfitLoss ? "To" : "As of"}<input name={isProfitLoss ? "to" : "asOf"} type="date" defaultValue={asOf.toISOString().slice(0, 10)} /></label><button className="button-secondary">Update</button></form><Link className="button-secondary report-pdf-button" href={`/reports/${type}/pdf?${pdfQuery}`}><Download size={17} /> Export PDF</Link><form action={publishReport}><input type="hidden" name="type" value={type}/><input type="hidden" name="from" value={from.toISOString()}/><input type="hidden" name="asOf" value={asOf.toISOString()}/><button className="button-primary">Publish to portal</button></form></div></header>{body}</main></AppShell>;
}

function Summary({ items }: { items: string[][] }) { return <div className="summary-grid">{items.map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>; }
function Statement({ title, rows, totalLabel, total }: { title: string; rows: string[][]; totalLabel: string; total: string }) { return <div className="statement-section"><h3>{title}</h3><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Account</th><th className="numeric">Amount</th></tr></thead><tbody>{rows.map(([code, name, amount]) => <tr key={`${code}-${name}`}><td>{code}</td><td>{name}</td><td className="numeric">{amount}</td></tr>)}<tr className="statement-total"><td colSpan={2}><strong>{totalLabel}</strong></td><td className="numeric"><strong>{total}</strong></td></tr></tbody></table></div></div>; }
function StandaloneTotal({ label, value }: { label: string; value: string }) { return <div className="statement-grand-total"><strong>{label}</strong><strong>{value}</strong></div>; }
function ReportTable({ heads, rows }: { heads: string[]; rows: (string | number)[][] }) { return <section className="surface-card table-card"><div className="data-table-wrap"><table className="data-table"><thead><tr>{heads.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className={j === row.length - 1 ? "numeric" : ""}>{cell}</td>)}</tr>)}{!rows.length && <tr><td colSpan={heads.length}>No posted data for this report period.</td></tr>}</tbody></table></div></section>; }
