import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AutoReferenceField } from "@/components/auto-reference-field";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";
import { createReconciliation } from "../actions";
export const dynamic = "force-dynamic";
export default async function NewReconciliationPage() { const { user, tenants, active } = await requireActiveTenant(); const accounts = await db.account.findMany({ where: { tenantId: active.id, isActive: true, type: "ASSET", reportingClassification: "Cash and cash equivalents" }, orderBy: { code: "asc" } }); const today = new Date().toISOString().slice(0, 10); return <AppShell user={{ displayName: user.displayName, email: user.email, role: user.staffRole?.replaceAll("_", " ") ?? "STAFF", firmName: user.firm.name }} tenants={tenants} activeTenant={active} pageTitle="New Bank Reconciliation" pageDescription="Enter the period and balance from the statement"><main className="module-page form-page"><Link href="/reconciliations" className="back-link"><ArrowLeft size={15}/>Back to reconciliations</Link><form action={createReconciliation} className="surface-card compact-form-body"><div className="card-header"><div><h3>Statement details</h3><p>Use the dates and closing balance printed on the bank or cash statement.</p></div></div><div className="form-grid"><label>Bank or cash account<select name="accountId" required defaultValue=""><option value="" disabled>Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label><AutoReferenceField example="REC-2026-0001"/><label>Statement start<input type="date" name="statementStart" required defaultValue={today}/></label><label>Statement end<input type="date" name="statementEnd" required defaultValue={today}/></label><label>Statement closing balance ({active.defaultCurrency})<input name="statementClosingBalance" required inputMode="decimal" placeholder="0.00"/></label></div><div className="form-actions"><Link href="/reconciliations" className="button-secondary">Cancel</Link><button className="button-primary">Continue to matching</button></div></form></main></AppShell>; }

