import Link from "next/link";
import { notFound } from "next/navigation";
import { changeSalesQuotationStatus, convertSalesQuotation, deleteSalesQuotation } from "@/app/sales/quotations/actions";
import { convertQuotationToSalesOrder } from "@/app/sales/orders/actions";
import { AppShell } from "@/components/app-shell";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";

export const dynamic = "force-dynamic";
export default async function SalesQuotationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { user, tenants, active } = await requireActiveTenant();
  const quotation = await db.salesQuotation.findFirst({ where: { id, tenantId: active.id }, include: { customer: true, lines: { include: { inventoryItem: true, inventoryLocation: true, revenueAccount: true } }, convertedInvoice: true, convertedOrder: true } });
  if (!quotation) notFound(); const currentDate = new Date(); const today = currentDate.toISOString().slice(0, 10); const dueDate = new Date(currentDate); dueDate.setUTCDate(dueDate.getUTCDate() + quotation.customer.paymentTermsDays); const due = dueDate.toISOString().slice(0, 10);
  const action = (status: string, label: string, style = "button-secondary") => <form action={changeSalesQuotationStatus}><input type="hidden" name="id" value={quotation.id} /><input type="hidden" name="status" value={status} /><button className={style}>{label}</button></form>;
  return <AppShell user={{ displayName: user.displayName, email: user.email, role: user.staffRole?.replaceAll("_", " ") || "STAFF", firmName: user.firm.name }} tenants={tenants} activeTenant={active} pageTitle={`Quotation ${quotation.reference}`} pageDescription="Review status, lines, and controlled invoice conversion"><main className="module-page"><header className="module-header"><div><Link className="back-link" href="/sales/quotations">← Sales quotations</Link><p className="eyebrow">{quotation.customer.name.toUpperCase()}</p><h2>{quotation.reference}</h2><p>{quotation.description}</p></div><span className={`status-badge large ${quotation.status.toLowerCase()}`}>{quotation.status}</span></header>
    <section className="surface-card report-summary-grid"><div><span>Quotation date</span><strong>{quotation.quoteDate.toLocaleDateString("en-BN")}</strong></div><div><span>Valid until</span><strong>{quotation.validUntil.toLocaleDateString("en-BN")}</strong></div><div><span>Currency</span><strong>{quotation.currency}</strong></div><div><span>Total</span><strong>{quotation.currency} {Number(quotation.foreignTotal).toFixed(2)}</strong></div></section>
    <section className="surface-card table-card"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Item</th><th>Location</th><th>Revenue account</th><th className="numeric">Qty</th><th className="numeric">Unit price</th><th className="numeric">Discount</th><th className="numeric">Net</th></tr></thead><tbody>{quotation.lines.map((line) => <tr key={line.id}><td>{line.description}</td><td>{line.inventoryItem?.name || "—"}</td><td>{line.inventoryLocation?.name || "—"}</td><td>{line.revenueAccount.code} — {line.revenueAccount.name}</td><td className="numeric">{Number(line.quantity)}</td><td className="numeric">{quotation.currency} {Number(line.unitPrice).toFixed(2)}</td><td className="numeric">{Number(line.discountPercent).toFixed(2)}%</td><td className="numeric money">{quotation.currency} {Number(line.lineTotal).toFixed(2)}</td></tr>)}</tbody></table></div></section>
    <section className="surface-card form-section"><div className="section-heading"><h2>Workflow</h2><p>Only conversion creates a posted invoice and ledger entry. Accepted quotations can be converted once.</p></div><div className="workflow-actions">{quotation.status === "DRAFT" && action("SENT", "Mark as sent", "button-primary")}{quotation.status === "SENT" && <>{action("ACCEPTED", "Accept", "button-primary")}{action("DECLINED", "Decline")}{action("EXPIRED", "Mark expired")}</>}{["DRAFT", "SENT", "ACCEPTED"].includes(quotation.status) && action("CANCELLED", "Cancel quotation")}</div>
      {quotation.status === "ACCEPTED" && <form action={convertSalesQuotation} className="form-grid quotation-convert"><input type="hidden" name="id" value={quotation.id} /><label>Invoice date<input name="invoiceDate" type="date" defaultValue={today} required /></label><label>Due date<input name="dueDate" type="date" defaultValue={due} required /></label><button className="button-primary">Convert to posted invoice</button></form>}
      {quotation.status === "ACCEPTED" && <form action={convertQuotationToSalesOrder} className="form-grid quotation-convert"><input type="hidden" name="id" value={quotation.id} /><label>Order date<input name="orderDate" type="date" defaultValue={today} required /></label><label>Expected fulfillment<input name="expectedDate" type="date" defaultValue={quotation.validUntil.toISOString().slice(0, 10)} required /></label><button className="button-secondary">Convert to sales order</button></form>}
      {quotation.convertedInvoice && <p>Converted to invoice <Link className="record-link" href={`/sales/${quotation.convertedInvoice.id}/edit`}>{quotation.convertedInvoice.reference}</Link>.</p>}
      {quotation.convertedOrder && <p>Converted to sales order <Link className="record-link" href={`/sales/orders/${quotation.convertedOrder.id}`}>{quotation.convertedOrder.reference}</Link>.</p>}
      {["DRAFT", "CANCELLED"].includes(quotation.status) && <form action={deleteSalesQuotation} className="form-grid quotation-delete"><input type="hidden" name="id" value={quotation.id} /><label>Deletion reason<input name="reason" minLength={5} required /></label><button className="button-danger">Delete quotation</button></form>}
    </section></main></AppShell>;
}
