"use server";
import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import { z } from "zod";
import type { ConsumptionState } from "@/components/monthly-inventory-consumption-form";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";
import { resolveReference } from "@/lib/reference-numbers";
import { issueInventory } from "@/lib/inventory-ledger";
const schema=z.object({reference:z.string().trim().max(40).default(""),autoReference:z.string().optional(),consumptionDate:z.coerce.date(),description:z.string().trim().min(2).max(240),entryMode:z.enum(["MANUAL","CSV"])}),zero=new Prisma.Decimal(0);
type CountRow={itemId?:string;locationId?:string;sku?:string;location?:string;closing:Prisma.Decimal;row:number};
function fields(row:string){const values:string[]=[];let value="",quoted=false;for(let i=0;i<row.length;i++){const char=row[i];if(char==='"'&&quoted&&row[i+1]==='"'){value+='"';i++}else if(char==='"')quoted=!quoted;else if(char===","&&!quoted){values.push(value.trim());value=""}else value+=char}values.push(value.trim());return values}
function decimal(value:string,label:string){let result:Prisma.Decimal;try{result=new Prisma.Decimal(value)}catch{throw new Error(`${label} is not a valid quantity.`)}if(result.lt(0)||result.decimalPlaces()>4)throw new Error(`${label} must be zero or positive with no more than four decimal places.`);return result}
async function rowsFromCsv(data:FormData):Promise<CountRow[]>{const file=data.get("consumptionFile");if(!(file instanceof File)||!file.size)throw new Error("Select a closing-stock CSV file.");if(file.size>2_000_000)throw new Error("The closing-stock file cannot exceed 2 MB.");const rows=(await file.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),headers=fields(rows[0]).map(x=>x.toLowerCase().replace(/[^a-z]/g,"")),skuIndex=headers.indexOf("sku"),locationIndex=headers.indexOf("location"),closingIndex=headers.indexOf("closingquantity");if([skuIndex,locationIndex,closingIndex].some(x=>x<0))throw new Error("CSV headers must include SKU, Location, and ClosingQuantity.");if(rows.length<2||rows.length>1001)throw new Error("Enter between 1 and 1,000 closing-stock rows.");return rows.slice(1).map((row,index)=>{const values=fields(row),sku=values[skuIndex]?.trim(),location=values[locationIndex]?.trim();if(!sku||!location)throw new Error(`CSV row ${index+2} requires an SKU and location.`);return{sku,location,closing:decimal(values[closingIndex]??"",`CSV row ${index+2} closing quantity`),row:index+2}})}
function rowsFromManual(data:FormData):CountRow[]{const itemIds=data.getAll("manualItemId").map(String),locationIds=data.getAll("manualLocationId").map(String),closings=data.getAll("manualClosingQuantity").map(String);if(itemIds.length!==locationIds.length||itemIds.length!==closings.length)throw new Error("Manual closing-stock rows are incomplete.");const result:CountRow[]=[];closings.forEach((value,index)=>{if(value.trim()!=="")result.push({itemId:itemIds[index],locationId:locationIds[index],closing:decimal(value,`Row ${index+1} closing quantity`),row:index+1})});return result}
export async function postMonthlyConsumption(_:ConsumptionState,data:FormData):Promise<ConsumptionState>{
 try{const{user,active}=await requireActiveTenant();if(!user.staffRole||!["SYSTEM_ADMIN","FIRM_ADMIN","ACCOUNTANT"].includes(user.staffRole))throw new Error("Your role cannot post inventory consumption.");const input=schema.parse(Object.fromEntries(data)),countRows=input.entryMode==="CSV"?await rowsFromCsv(data):rowsFromManual(data);if(!countRows.length)throw new Error("Enter at least one physical closing quantity.");const keys=countRows.map(row=>row.itemId&&row.locationId?`${row.itemId}:${row.locationId}`:`${row.sku}:${row.location}`);if(new Set(keys).size!==keys.length)throw new Error("Each item and location can appear only once.");
 input.reference=await resolveReference({tenantId:active.id,kind:"MONTHLY_INVENTORY",date:input.consumptionDate,supplied:input.reference,auto:input.autoReference==="true"});
 await db.$transaction(async tx=>{const period=await tx.accountingPeriod.findFirst({where:{tenantId:active.id,status:"OPEN",startsOn:{lte:input.consumptionDate},endsOn:{gte:input.consumptionDate}},orderBy:{startsOn:"desc"}});if(!period)throw new Error("No open accounting period contains the consumption date. Open the required period and try again.");if(await tx.journal.findFirst({where:{tenantId:active.id,reference:input.reference}}))throw new Error(`Reference ${input.reference} already exists.`);
 const items=await tx.inventoryItem.findMany({where:{tenantId:active.id,isActive:true,...(input.entryMode==="CSV"?{sku:{in:[...new Set(countRows.map(x=>x.sku!))]}}:{id:{in:[...new Set(countRows.map(x=>x.itemId!))]}})}}),locations=await tx.inventoryLocation.findMany({where:{tenantId:active.id,isActive:true,...(input.entryMode==="CSV"?{code:{in:[...new Set(countRows.map(x=>x.location!))]}}:{id:{in:[...new Set(countRows.map(x=>x.locationId!))]}})}}),itemMap=new Map(items.flatMap(item=>[[item.id,item],[item.sku,item]])),locationMap=new Map(locations.flatMap(location=>[[location.id,location],[location.code,location]])),journalLines:{accountId:string;debit:Prisma.Decimal;credit:Prisma.Decimal;description:string}[]=[];let totalCost=zero,postedRows=0;
 for(const row of countRows){const item=itemMap.get(row.itemId??row.sku!),location=locationMap.get(row.locationId??row.location!);if(!item)throw new Error(`Row ${row.row}: inventory item was not found or is inactive.`);if(!location)throw new Error(`Row ${row.row}: stock location was not found or is inactive.`);const balance=await tx.inventoryBalance.findUnique({where:{itemId_locationId:{itemId:item.id,locationId:location.id}}});if(!balance)throw new Error(`Row ${row.row}: no stock balance exists for ${item.name} at ${location.name}.`);if(row.closing.gt(balance.quantity))throw new Error(`Row ${row.row}: closing quantity for ${item.name} exceeds the book quantity. Use a stock adjustment to record an increase.`);const consumed=balance.quantity.sub(row.closing);if(consumed.eq(0))continue;const issued=await issueInventory(tx,{tenantId:active.id,costingMethod:active.inventoryCostingMethod,itemId:item.id,locationId:location.id,quantity:consumed});await tx.inventoryMovement.create({data:{tenantId:active.id,itemId:item.id,locationId:location.id,type:"ADJUSTMENT_OUT",movementDate:input.consumptionDate,quantity:consumed.neg(),unitCost:issued.unitCost,totalCost:issued.cost.neg(),reference:input.reference,sourceType:"MonthlyInventoryConsumption",sourceId:input.reference,notes:input.description,createdById:user.id}});journalLines.push({accountId:item.cogsAccountId,debit:issued.cost,credit:zero,description:`Monthly consumption — ${item.name}`},{accountId:item.inventoryAccountId,debit:zero,credit:issued.cost,description:`Inventory consumed — ${item.name}`});totalCost=totalCost.add(issued.cost);postedRows++}
 if(!postedRows)throw new Error("The entered closing quantities equal the current book quantities; there is no consumption to post.");const journal=await tx.journal.create({data:{tenantId:active.id,periodId:period.id,reference:input.reference,description:input.description,accountingDate:input.consumptionDate,status:"POSTED",source:"INVENTORY_ADJUSTMENT",sourceId:input.reference,createdById:user.id,approvedById:user.id,postedById:user.id,postedAt:new Date(),lines:{create:journalLines}}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"MONTHLY_INVENTORY_CONSUMPTION_POSTED",entityType:"Journal",entityId:journal.id,newValues:{reference:input.reference,entryMode:input.entryMode,countRows:countRows.length,consumedRows:postedRows,totalCost:totalCost.toString(),revenuePosted:false}}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }catch(error){return{error:error instanceof Error?error.message:"Monthly inventory consumption could not be posted."}}redirect("/inventory/movements")
}
