export const bruneiChart = [
  ["1000","Cash on hand","ASSET","Cash and cash equivalents",false],["1100","Cash at bank","ASSET","Cash and cash equivalents",false],["1110","Petty cash","ASSET","Cash and cash equivalents",false],
  ["1200","Trade receivables","ASSET","Current assets",true],["1210","Allowance for doubtful debts","ASSET","Current assets",false],["1300","Inventory","ASSET","Current assets",true],["1400","Prepayments","ASSET","Current assets",false],["1410","Staff advances","ASSET","Current assets",false],
  ["1500","Property, plant and equipment","ASSET","Non-current assets",false],["1510","Accumulated depreciation","ASSET","Non-current assets",true],["1600","Security deposits","ASSET","Non-current assets",false],
  ["2000","Trade payables","LIABILITY","Current liabilities",true],["2200","Accrued expenses","LIABILITY","Current liabilities",false],["2210","Payroll payable","LIABILITY","Employee obligations",true],["2220","SPK contributions payable","LIABILITY","Employee obligations",true],["2230","Corporate income tax payable","LIABILITY","Current liabilities",true],["2300","Short-term borrowings","LIABILITY","Borrowings",false],["2500","Long-term loans","LIABILITY","Non-current liabilities",false],
  ["3000","Share capital / owner capital","EQUITY","Equity"],["3100","Retained earnings","EQUITY","Equity"],["3300","Drawings / distributions","EQUITY","Equity"],
  ["4000","Sales revenue","REVENUE","Operating revenue"],["4100","Service revenue","REVENUE","Operating revenue"],["4200","Other operating income","REVENUE","Other income"],["4300","Finance income","REVENUE","Other income"],
  ["4310","Foreign exchange gains (losses)","REVENUE","Other income"],
  ["5000","Cost of sales","EXPENSE","Direct costs"],["5100","Direct labour","EXPENSE","Direct costs"],["5200","Freight and delivery","EXPENSE","Direct costs"],
  ["6000","Salaries and wages","EXPENSE","Operating expenses"],["6010","Employer SPK contributions","EXPENSE","Operating expenses"],["6100","Rent and premises","EXPENSE","Operating expenses"],["6200","Utilities","EXPENSE","Operating expenses"],["6300","Office and administration","EXPENSE","Operating expenses"],["6400","Professional fees","EXPENSE","Operating expenses"],["6500","Repairs and maintenance","EXPENSE","Operating expenses"],["6600","Travel and transport","EXPENSE","Operating expenses"],["6700","Marketing and promotion","EXPENSE","Operating expenses"],["6800","Bank charges","EXPENSE","Finance costs"],["6900","Depreciation expense","EXPENSE","Operating expenses"],["7000","Corporate income tax expense","EXPENSE","Income tax"],
  ["6810","Cash over and short","EXPENSE","Operating expenses"],
] as const;
