ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'SCAN_PENDING' BEFORE 'UPLOADED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'QUARANTINED' BEFORE 'UPLOADED';

ALTER TABLE "Document"
ADD COLUMN "scannedAt" TIMESTAMP(3),
ADD COLUMN "scanEngine" TEXT,
ADD COLUMN "scanResult" TEXT,
ADD COLUMN "quarantineReason" TEXT;
