import Link from "next/link";
import { notFound } from "next/navigation";
import { changeSalesOrderStatus, convertSalesOrderToInvoice, deleteSalesOrder } from "@/app/sales/orders/actions";
import { AppShell } from "@/components/app-shell";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";

export const dynamic = "force-dynamic";
export default async function SalesOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { user, tenants, active } = await requireActiveTenant(); const order = await db.salesOrder.findFirst({ where: { id, tenantId: active.id }, include: { customer: true, quotation: true, convertedInvoice: true, lines: { include: { inventoryItem: true, inventoryLocation: true, revenueAccount: true } } } }); if (!order) notFound();
  const currentDate = new Date(); const today = currentDate.toISOString().slice(0, 10); const dueDate = new Date(currentDate); dueDate.setUTCDate(dueDate.getUTCDate() + order.customer.paymentTermsDays); const due = dueDate.toISOString().slice(0, 10); const action = (status: string, label: string, style = "button-secondary") => <form action={changeSalesOrderStatus}><input type="hidden" name="id" value={order.id} /><input type="hidden" name="status" value={status} /><button className={style}>{label}</button></form>;
  return <AppShell user={{ displayName: user.displayName, email: user.email, role: user.staffRole?.replaceAll("_", " ") || "STAFF", firmName: user.firm.name }} tenants={tenants} activeTenant={active} pageTitle={`Sales Order ${order.reference}`} pageDescription="Review commitment, fulfillment readiness, and invoice conversion"><main className="module-page"><header className="module-header"><div><Link className="back-link" href="/sales/orders">← Sales orders</Link><p className="eyebrow">{order.customer.name.toUpperCase()}</p><h2>{order.reference}</h2><p>{order.description}</p></div><span className={`status-badge large ${order.status.toLowerCase()}`}>{order.status.replaceAll("_", " ")}</span></header>
  <section className="surface-card report-summary-grid"><div><span>Order date</span><strong>{order.orderDate.toLocaleDateString("en-BN")}</strong></div><div><span>Expected fulfillment</span><strong>{order.expectedDate?.toLocaleDateString("en-BN") || "—"}</strong></div><div><span>Source</span><strong>{order.quotation ? <Link className="record-link" href={`/sales/quotations/${order.quotation.id}`}>{order.quotation.reference}</Link> : "Direct order"}</strong></div><div><span>Total</span><strong>{order.currency} {Number(order.foreignTotal).toFixed(2)}</strong></div></section>
  <section className="surface-card table-card"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Item</th><th>Location</th><th>Revenue account</th><th className="numeric">Qty</th><th className="numeric">Unit price</th><th className="numeric">Discount</th><th className="numeric">Net</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.id}><td>{line.description}</td><td>{line.inventoryItem?.name || "—"}</td><td>{line.inventoryLocation?.name || "—"}</td><td>{line.revenueAccount.code} — {line.revenueAccount.name}</td><td className="numeric">{Number(line.quantity)}</td><td className="numeric">{order.currency} {Number(line.unitPrice).toFixed(2)}</td><td className="numeric">{Number(line.discountPercent).toFixed(2)}%</td><td className="numeric money">{order.currency} {Number(line.lineTotal).toFixed(2)}</td></tr>)}</tbody></table></div></section>
  <section className="surface-card form-section"><div className="section-heading"><h2>Order workflow</h2><p>Confirmation and readiness remain non-ledger states. Conversion posts the invoice and connected inventory movements once.</p></div><div className="workflow-actions">{order.status === "DRAFT" && action("CONFIRMED", "Confirm order", "button-primary")}{order.status === "CONFIRMED" && action("READY_TO_INVOICE", "Mark ready to invoice", "button-primary")}{["DRAFT", "CONFIRMED", "READY_TO_INVOICE"].includes(order.status) && action("CANCELLED", "Cancel order")}</div>
  {order.status === "READY_TO_INVOICE" && <form action={convertSalesOrderToInvoice} className="form-grid quotation-convert"><input type="hidden" name="id" value={order.id} /><label>Invoice date<input name="invoiceDate" type="date" defaultValue={today} required /></label><label>Due date<input name="dueDate" type="date" defaultValue={due} required /></label><button className="button-primary">Convert to posted invoice</button></form>}
  {order.convertedInvoice && <p>Converted to invoice <Link className="record-link" href={`/sales/${order.convertedInvoice.id}/edit`}>{order.convertedInvoice.reference}</Link>.</p>}
  {["DRAFT", "CANCELLED"].includes(order.status) && <form action={deleteSalesOrder} className="form-grid quotation-delete"><input type="hidden" name="id" value={order.id} /><label>Deletion reason<input name="reason" minLength={5} required /></label><button className="button-danger">Delete sales order</button></form>}</section></main></AppShell>;
}
