import Link from "next/link";
import { notFound } from "next/navigation";
import { Pencil } from "lucide-react";
import { Prisma } from "@prisma/client";
import { AppShell } from "@/components/app-shell";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";

export const dynamic = "force-dynamic";
const zero = new Prisma.Decimal(0);
const parseDate = (value?: string) => { const parsed = value ? new Date(`${value}T23:59:59.999Z`) : new Date(); return Number.isNaN(parsed.getTime()) ? new Date() : parsed; };
const quantity = (value: Prisma.Decimal) => Number(value).toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 4 });
const money = (currency: string, value: Prisma.Decimal, decimals = 2) => `${currency} ${Number(value).toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;

export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ asOf?: string }> }) {
  const { id } = await params, query = await searchParams, { user, tenants, active } = await requireActiveTenant(), asOf = parseDate(query.asOf);
  const item = await db.inventoryItem.findFirst({ where: { id, tenantId: active.id }, include: { inventoryAccount: true, revenueAccount: true, cogsAccount: true } });
  if (!item) notFound();
  const movements = await db.inventoryMovement.findMany({ where: { tenantId: active.id, itemId: item.id, movementDate: { lte: asOf } }, include: { location: true }, orderBy: [{ movementDate: "asc" }, { createdAt: "asc" }] });
  const { rows, runningQuantity, runningValue } = movements.reduce((state, movement) => { const nextQuantity = state.runningQuantity.add(movement.quantity), nextValue = state.runningValue.add(movement.totalCost); return { runningQuantity: nextQuantity, runningValue: nextValue, rows: [...state.rows, { ...movement, sourceType: movement.sourceType ?? "Manual", runningQuantity: nextQuantity, runningValue: nextValue }] }; }, { runningQuantity: zero, runningValue: zero, rows: [] as Array<(typeof movements)[number] & { sourceType: string; runningQuantity: Prisma.Decimal; runningValue: Prisma.Decimal }> });
  const locationMap = new Map<string, { code: string; name: string; quantity: Prisma.Decimal; value: Prisma.Decimal }>();
  for (const movement of movements) { const current = locationMap.get(movement.locationId) ?? { code: movement.location.code, name: movement.location.name, quantity: zero, value: zero }; current.quantity = current.quantity.add(movement.quantity); current.value = current.value.add(movement.totalCost); locationMap.set(movement.locationId, current); }
  const averageCost = runningQuantity.eq(0) ? zero : runningValue.div(runningQuantity), dateKey = asOf.toISOString().slice(0, 10);
  return <AppShell user={{ displayName: user.displayName, email: user.email, role: user.staffRole?.replaceAll("_", " ") ?? "STAFF", firmName: user.firm.name }} tenants={tenants} activeTenant={active} pageTitle={`${item.sku} · ${item.name}`} pageDescription="Complete inventory item movement and valuation history">
    <main className="module-page">
      <div className="detail-toolbar"><Link href={`/reports/inventory-quantity-summary?asOf=${dateKey}`} className="back-link">← Inventory Quantity Summary</Link><Link href={`/inventory/items/${item.id}/edit`} className="button-secondary"><Pencil size={15} />Edit item</Link></div>
      <header className="module-header"><div><p className="eyebrow">{item.sku}</p><h2>{item.name}</h2><p>{item.description || "Inventory item"} · Unit: {item.unitName}</p></div><form className="report-filter"><label>As of<input name="asOf" type="date" defaultValue={dateKey} /></label><button className="button-secondary">Update</button></form></header>
      <section className="summary-grid"><div><small>Quantity on hand</small><strong>{quantity(runningQuantity)} {item.unitName}</strong></div><div><small>Average cost</small><strong>{money(active.defaultCurrency, averageCost, 4)}</strong></div><div><small>Inventory value</small><strong>{money(active.defaultCurrency, runningValue)}</strong></div><div><small>Movements</small><strong>{movements.length}</strong></div></section>
      <section className="surface-card table-card"><div className="card-header"><div><h3>Balance by location</h3><p>Quantity and value held at each stock location.</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Location</th><th className="numeric">Quantity</th><th className="numeric">Average cost</th><th className="numeric">Value</th></tr></thead><tbody>{[...locationMap.values()].map((location) => <tr key={location.code}><td><strong>{location.code}</strong> · {location.name}</td><td className="numeric">{quantity(location.quantity)}</td><td className="numeric">{money(active.defaultCurrency, location.quantity.eq(0) ? zero : location.value.div(location.quantity), 4)}</td><td className="numeric">{money(active.defaultCurrency, location.value)}</td></tr>)}{!locationMap.size && <tr><td colSpan={4}>No stock movements recorded.</td></tr>}</tbody></table></div></section>
      <section className="surface-card table-card"><div className="card-header"><div><h3>Item movement ledger</h3><p>Every stock increase and decrease with running quantity and value.</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Location</th><th>Source</th><th className="numeric">Movement qty</th><th className="numeric">Unit cost</th><th className="numeric">Movement value</th><th className="numeric">Running qty</th><th className="numeric">Running value</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.movementDate.toLocaleDateString("en-BN")}</td><td><strong>{row.reference}</strong></td><td>{row.type.replaceAll("_", " ")}</td><td>{row.location.code}</td><td>{row.sourceType.replaceAll(/([a-z])([A-Z])/g, "$1 $2")}</td><td className="numeric">{quantity(row.quantity)}</td><td className="numeric">{money(active.defaultCurrency, row.unitCost, 4)}</td><td className="numeric">{money(active.defaultCurrency, row.totalCost)}</td><td className="numeric"><strong>{quantity(row.runningQuantity)}</strong></td><td className="numeric"><strong>{money(active.defaultCurrency, row.runningValue)}</strong></td></tr>)}{!rows.length && <tr><td colSpan={10}>No movements recorded for this item.</td></tr>}</tbody></table></div></section>
      <section className="surface-card"><div className="card-header"><div><h3>Account mappings</h3><p>Accounts used automatically when this item is purchased or sold.</p></div></div><div className="summary-grid"><div><small>Inventory</small><strong>{item.inventoryAccount.code} · {item.inventoryAccount.name}</strong></div><div><small>Sales revenue</small><strong>{item.revenueAccount.code} · {item.revenueAccount.name}</strong></div><div><small>Cost of sales</small><strong>{item.cogsAccount.code} · {item.cogsAccount.name}</strong></div></div></section>
    </main>
  </AppShell>;
}
