"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { Prisma } from "@prisma/client";import { db } from "@/lib/db";
import { z } from "zod";
import { requireActiveTenant } from "@/lib/session";
import { postSettlement } from "@/lib/settlements";
import { resolveReference } from "@/lib/reference-numbers";
import { postDirectReceipt } from "@/lib/receipts";

const schema=z.object({partyId:z.string().min(1),bankAccountId:z.string().min(1),reference:z.string().trim().max(40).default(""),autoReference:z.string().optional(),settlementDate:z.coerce.date(),paymentMethod:z.enum(["BANK_TRANSFER","BANK_CHEQUE","CASH","OTHER"]).optional(),chequeNumber:z.string().trim().max(60).optional(),chequeDate:z.coerce.date().optional()});
async function post(kind:"RECEIPT"|"PAYMENT",formData:FormData){const{user,active}=await requireActiveTenant();const header=schema.parse(Object.fromEntries(formData));const reference=await resolveReference({tenantId:active.id,kind:kind==="RECEIPT"?"CUSTOMER_RECEIPT":"SUPPLIER_PAYMENT",date:header.settlementDate,supplied:header.reference,auto:header.autoReference==="true"});const ids=formData.getAll("documentId").map(String);const amounts=formData.getAll("allocationAmount").map(String);const submittedDiscounts=formData.getAll("discountInput").map(String);const discounts=submittedDiscounts.length?submittedDiscounts:ids.map(()=>"");if(ids.length!==amounts.length||ids.length!==discounts.length)throw new Error("Settlement allocations are incomplete.");const allocations=ids.map((documentId,i)=>({documentId,amount:amounts[i],discountInput:discounts[i]})).filter(a=>a.amount.trim()!==""||a.discountInput.trim()!=="");await postSettlement({kind,actor:{tenantId:active.id,userId:user.id,firmId:user.firmId,role:user.staffRole},partyId:header.partyId,bankAccountId:header.bankAccountId,reference,settlementDate:header.settlementDate,allocations,paymentMethod:header.paymentMethod,chequeNumber:header.chequeNumber,chequeDate:header.chequeDate});redirect(kind==="RECEIPT"?"/receipts":"/payments");}
const receiptSchema=z.object({receiptMode:z.enum(["LINES","INVOICES"]),payerType:z.enum(["CUSTOMER","OTHER"]),partyId:z.string().optional(),payerName:z.string().trim().max(160).optional(),bankAccountId:z.string().min(1),reference:z.string().trim().max(40).default(""),autoReference:z.string().optional(),settlementDate:z.coerce.date(),description:z.string().trim().max(500).default(""),currency:z.string().trim().min(3).max(3).optional()});
export async function postReceipt(formData:FormData){
  const{user,active}=await requireActiveTenant();
  const header=receiptSchema.parse(Object.fromEntries(formData));
  const reference=await resolveReference({tenantId:active.id,kind:"CUSTOMER_RECEIPT",date:header.settlementDate,supplied:header.reference,auto:header.autoReference==="true"});
  if(header.receiptMode==="INVOICES"){
    if(!header.partyId)throw new Error("Select a customer.");
    const ids=formData.getAll("documentId").map(String),amounts=formData.getAll("allocationAmount").map(String),discounts=formData.getAll("discountInput").map(String);
    if(ids.length!==amounts.length||ids.length!==discounts.length)throw new Error("Receipt allocations are incomplete.");
    const allocations=ids.map((documentId,i)=>({documentId,amount:amounts[i],discountInput:discounts[i]})).filter(a=>a.amount.trim()!==""||a.discountInput.trim()!=="");
    await postSettlement({kind:"RECEIPT",actor:{tenantId:active.id,userId:user.id,firmId:user.firmId,role:user.staffRole},partyId:header.partyId,bankAccountId:header.bankAccountId,reference,settlementDate:header.settlementDate,allocations});
  }else{
    const accountIds=formData.getAll("lineAccountId").map(String),descriptions=formData.getAll("lineDescription").map(String),quantities=formData.getAll("lineQuantity").map(String),unitPrices=formData.getAll("lineUnitPrice").map(String);
    if(!accountIds.length||accountIds.length!==descriptions.length||accountIds.length!==quantities.length||accountIds.length!==unitPrices.length)throw new Error("Receipt line items are incomplete.");
    await postDirectReceipt({actor:{tenantId:active.id,userId:user.id,firmId:user.firmId,role:user.staffRole},bankAccountId:header.bankAccountId,customerId:header.partyId,payerType:header.payerType,payerName:header.payerName,reference,receiptDate:header.settlementDate,description:header.description,currency:header.currency??active.defaultCurrency,lines:accountIds.map((accountId,index)=>({accountId,description:descriptions[index],quantity:quantities[index],unitPrice:unitPrices[index]}))});
  }
  revalidatePath("/receipts");revalidatePath("/journals");revalidatePath("/");redirect("/receipts");
}
export async function postPayment(formData:FormData){return post("PAYMENT",formData)}
async function updateReference(kind:"RECEIPT"|"PAYMENT",formData:FormData){const{user,active}=await requireActiveTenant();if(!user.staffRole||!["SYSTEM_ADMIN","FIRM_ADMIN","ACCOUNTANT"].includes(user.staffRole))throw new Error("Your role cannot update settlements.");const input=z.object({id:z.string().min(1),reference:z.string().trim().min(1).max(40),reason:z.string().trim().min(5).max(240)}).parse(Object.fromEntries(formData));await db.$transaction(async tx=>{const record=kind==="RECEIPT"?await tx.customerReceipt.findFirst({where:{id:input.id,tenantId:active.id}}):await tx.supplierPayment.findFirst({where:{id:input.id,tenantId:active.id}});if(!record)throw new Error("Settlement not found.");if(kind==="RECEIPT")await tx.customerReceipt.update({where:{id:record.id},data:{reference:input.reference}});else await tx.supplierPayment.update({where:{id:record.id},data:{reference:input.reference}});if(record.journalId)await tx.journal.update({where:{id:record.journalId},data:{reference:input.reference}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:kind==="RECEIPT"?"CUSTOMER_RECEIPT_UPDATED":"SUPPLIER_PAYMENT_UPDATED",entityType:kind==="RECEIPT"?"CustomerReceipt":"SupplierPayment",entityId:record.id,previousValues:{reference:record.reference},newValues:{reference:input.reference},reason:input.reason}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});const path=kind==="RECEIPT"?"/receipts":"/payments";revalidatePath(path);revalidatePath("/journals");redirect(path)}
export async function updateReceipt(formData:FormData){return updateReference("RECEIPT",formData)}export async function updateSupplierPayment(formData:FormData){return updateReference("PAYMENT",formData)}
