import Link from "next/link";
import { Download } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { db } from "@/lib/db";
import { formatCurrencyAmount } from "@/lib/currency";
import { payrollEntriesForPeriod, payrollEntryGross, payrollReportTotals } from "@/lib/payroll-reports";
import { requireActiveTenant } from "@/lib/session";

export const dynamic = "force-dynamic";
const parsed = (value: string | undefined, fallback: Date) => value ? new Date(`${value}T00:00:00`) : fallback;
const money = formatCurrencyAmount;

export default async function Page({ searchParams }: { searchParams: Promise<{ employeeId?: string; from?: string; to?: string }> }) {
  const query = await searchParams, { user, tenants, active } = await requireActiveTenant(), now = new Date();
  const from = parsed(query.from, new Date(now.getFullYear(), 0, 1)), to = parsed(query.to, now);
  const employees = await db.employee.findMany({ where: { tenantId: active.id }, orderBy: { fullName: "asc" } });
  const employeeId = employees.some(employee => employee.id === query.employeeId) ? query.employeeId! : employees[0]?.id;
  const employee = employees.find(item => item.id === employeeId);
  const entries = employeeId ? (await payrollEntriesForPeriod(active.id, from, to)).filter(entry => entry.employeeId === employeeId) : [];
  const totals = payrollReportTotals(entries), range = `employeeId=${employeeId ?? ""}&from=${from.toISOString().slice(0, 10)}&to=${to.toISOString().slice(0, 10)}`;
  return <AppShell user={{ displayName:user.displayName,email:user.email,role:user.staffRole?.replaceAll("_"," ")??"STAFF",firmName:user.firm.name }} tenants={tenants} activeTenant={active} pageTitle="Employee Statement" pageDescription="Posted payroll and opening YTD figures for one employee"><main className="module-page"><div className="detail-toolbar"><Link href="/reports" className="back-link">← Report library</Link></div><header className="module-header"><div><p className="eyebrow">{active.legalName.toUpperCase()}</p><h2>Employee Statement</h2><p>{employee ? `${employee.employeeNumber} · ${employee.fullName}` : "No employee selected"}</p></div><div className="report-actions"><form className="report-filter"><label>Employee<select name="employeeId" defaultValue={employeeId}>{employees.map(item=><option value={item.id} key={item.id}>{item.employeeNumber} · {item.fullName}</option>)}</select></label><label>From<input name="from" type="date" defaultValue={from.toISOString().slice(0,10)}/></label><label>To<input name="to" type="date" defaultValue={to.toISOString().slice(0,10)}/></label><button className="button-secondary">Update</button></form>{employeeId&&<Link className="button-secondary" href={`/reports/employee-statement/pdf?${range}`}><Download size={16}/>Export PDF</Link>}</div></header><div className="summary-grid"><div><small>Pay entries</small><strong>{entries.length}</strong></div><div><small>Gross pay</small><strong>{money(active.defaultCurrency,totals.gross)}</strong></div><div><small>Employee SPK</small><strong>{money(active.defaultCurrency,totals.employeeSpk)}</strong></div><div><small>Net pay</small><strong>{money(active.defaultCurrency,totals.net)}</strong></div></div><section className="surface-card table-card"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Pay date</th><th>Reference</th><th>Type</th><th className="numeric">Gross</th><th className="numeric">Employee SPK</th><th className="numeric">Other deductions</th><th className="numeric">Net pay</th></tr></thead><tbody>{entries.map(entry=><tr key={`${entry.isOpeningYtd?"opening":"payroll"}-${entry.id}`}><td>{entry.reportDate.toLocaleDateString("en-BN")}</td><td>{entry.reportRunId?<Link className="record-link" href={`/payroll/runs/${entry.reportRunId}`}>{entry.reportReference}</Link>:<strong>{entry.reportReference}</strong>}</td><td>{entry.reportType}</td><td className="numeric">{money(active.defaultCurrency,payrollEntryGross(entry))}</td><td className="numeric">{money(active.defaultCurrency,entry.employeeSpk)}</td><td className="numeric">{money(active.defaultCurrency,entry.otherDeductions)}</td><td className="numeric"><strong>{money(active.defaultCurrency,entry.netPay)}</strong></td></tr>)}{!entries.length&&<tr><td colSpan={7} className="table-empty">No payroll or opening YTD entries for this employee and period.</td></tr>}</tbody></table></div></section></main></AppShell>;
}
