"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { Maximize2, Minimize2, Plus, Trash2 } from "lucide-react";
import { useActionState, useEffect, useState } from "react";
import type { DailySaleActionState } from "@/app/cash-sales/actions";
import { AutoReferenceField } from "@/components/auto-reference-field";
import { QuickInventoryItemButton, type InventoryMappingAccount } from "@/components/quick-inventory-item";

type Account = { id: string; code: string; name: string };
type Item = Account & { revenueAccountId: string };
type DiscountType = "NONE" | "PERCENT" | "AMOUNT";
type Line = { id: number; description: string; accountId: string; itemId: string; locationId: string; quantity: string; price: string; discountType: DiscountType; discount: string };
type Tender = { id: number; type: string; accountId: string; amount: string; reference: string };
export type DailySaleFormInitial = { id: string; reference: string; registerDate: string; branchLabel: string; registerLabel: string; lines: Omit<Line, "id">[]; tenders: Omit<Tender, "id">[] };
const emptyLine = (id: number): Line => ({ id, description: "", accountId: "", itemId: "", locationId: "", quantity: "1", price: "", discountType: "NONE", discount: "0" });

export function CashSalesForm({ action: submitAction, revenueAccounts, cashAccounts, inventoryItems: initialItems, inventoryLocations, branches, currency, initial, submitLabel = "Post daily sale", mappingAccounts = [] }: { action: (state: DailySaleActionState, data: FormData) => Promise<DailySaleActionState>; revenueAccounts: Account[]; cashAccounts: Account[]; inventoryItems: Item[]; inventoryLocations: Account[]; branches: string[]; currency: string; initial?: DailySaleFormInitial; submitLabel?: string; mappingAccounts?: InventoryMappingAccount[] }) {
  const router = useRouter();
  const [state, action, pending] = useActionState(submitAction, {});
  const [lines, setLines] = useState<Line[]>(initial?.lines.map((line, index) => ({ ...line, id: index + 1 })) ?? [emptyLine(1)]);
  const [inventoryItems, setInventoryItems] = useState(initialItems), [quickLineId, setQuickLineId] = useState(1);
  const [tenders, setTenders] = useState<Tender[]>(initial?.tenders.map((tender, index) => ({ ...tender, id: index + 1 })) ?? [{ id: 1, type: "CASH", accountId: "", amount: "", reference: "" }]);
  const [linesExpanded, setLinesExpanded] = useState(false);
  useEffect(() => { if (state.redirectTo) { router.replace(state.redirectTo); router.refresh(); } }, [router, state.redirectTo]);
  useEffect(() => {
    if (!linesExpanded) return;
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") setLinesExpanded(false); };
    window.addEventListener("keydown", close);
    return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", close); };
  }, [linesExpanded]);
  const amounts = (line: Line) => { const gross = (Number(line.quantity) || 0) * (Number(line.price) || 0), entered = Number(line.discount) || 0, discount = line.discountType === "PERCENT" ? gross * entered / 100 : line.discountType === "AMOUNT" ? entered : 0; return { gross, discount: Math.min(Math.max(discount, 0), gross), net: Math.max(gross - discount, 0) }; };
  const grossSales = lines.reduce((sum, line) => sum + amounts(line).gross, 0), discountTotal = lines.reduce((sum, line) => sum + amounts(line).discount, 0), sales = lines.reduce((sum, line) => sum + amounts(line).net, 0), tenderTotal = tenders.reduce((sum, tender) => sum + (Number(tender.amount) || 0), 0), tenderDifference = tenderTotal - sales;
  const update = (id: number, field: keyof Omit<Line, "id">, value: string) => setLines((rows) => rows.map((row) => row.id === id ? { ...row, [field]: value } : row));
  return <form action={action} className="form-panel">{initial && <input type="hidden" name="id" value={initial.id} />}{state.error && <div className="form-error" role="alert">{state.error}</div>}
    <section className="form-section"><div className="section-heading"><h2>Daily sales details</h2><p>The sale date automatically selects the matching open accounting period.</p></div><div className="form-grid">
      {initial?<label>Reference<input name="reference" required defaultValue={initial.reference}/></label>:<AutoReferenceField example="DS-2026-0001"/>}<label>Sale date<input name="registerDate" type="date" defaultValue={initial?.registerDate ?? new Date().toISOString().slice(0, 10)} required /></label>
      <label>Branch / location<select name="branchLabel" required defaultValue={initial?.branchLabel ?? ""}><option value="">Select branch</option>{branches.map((branch) => <option key={branch} value={branch}>{branch}</option>)}</select></label><label>Register / shift<input name="registerLabel" placeholder="Counter 1 — Day shift" defaultValue={initial?.registerLabel} /></label>
      {initial && <label className="span-2">Reason for update<input name="reason" required minLength={5} maxLength={240} placeholder="Explain what was corrected" /></label>}
    </div></section>
    <div className={`commercial-line-section cash-sales-posting-window${linesExpanded ? " is-expanded" : ""}`}>{linesExpanded && state.error && <div className="form-error" role="alert">{state.error}</div>}
    <section className="form-section cash-sales-line-section"><div className="section-heading line-heading"><div><h2>Sales lines</h2><p>Choose percentage or fixed-amount discount for each line.</p></div><div className="line-heading-actions"><button type="button" className="button-secondary" aria-expanded={linesExpanded} onClick={() => setLinesExpanded((value) => !value)}>{linesExpanded ? <><Minimize2 size={15} />Close sub-window</> : <><Maximize2 size={15} />Open in sub-window</>}</button>{!initial && <QuickInventoryItemButton accounts={mappingAccounts} onCreated={(item) => { setInventoryItems((current) => [...current, { id: item.id, code: item.sku, name: item.name, revenueAccountId: item.revenueAccountId }]); setLines((rows) => rows.map((line) => line.id === quickLineId ? { ...line, itemId: item.id, accountId: item.revenueAccountId, description: line.description || item.name } : line)); }} />}<button type="button" className="button-secondary" onClick={() => setLines((rows) => { const id = Math.max(...rows.map((row) => row.id)) + 1; setQuickLineId(id); return [...rows, emptyLine(id)]; })}><Plus size={15} />Add line</button></div></div>
      <div className="data-table-wrap cash-sales-lines-wrap"><table className="data-table commercial-line-table cash-sales-lines"><colgroup><col className="sale-description" /><col className="sale-item" /><col className="sale-location" /><col className="sale-account" /><col className="sale-qty" /><col className="sale-price" /><col className="sale-discount" /><col className="sale-net" /><col className="sale-action" /></colgroup><thead><tr><th>Description</th><th>Inventory item</th><th>Location</th><th>Revenue account</th><th>Qty</th><th>Unit price</th><th>Discount</th><th className="numeric">Net amount</th><th /></tr></thead><tbody>{lines.map((line) => <tr key={line.id} onFocus={() => setQuickLineId(line.id)}>
        <td><input name="lineDescription" value={line.description} onChange={(event) => update(line.id, "description", event.target.value)} required /></td>
        <td><select name="lineItemId" value={line.itemId} onChange={(event) => { const item = inventoryItems.find((entry) => entry.id === event.target.value); setLines((rows) => rows.map((entry) => entry.id === line.id ? { ...entry, itemId: event.target.value, accountId: item?.revenueAccountId ?? entry.accountId, description: item?.name || entry.description } : entry)); }}><option value="">Non-inventory sale</option>{inventoryItems.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></td>
        <td><select name="lineLocationId" value={line.locationId} disabled={!line.itemId} required={Boolean(line.itemId)} onChange={(event) => update(line.id, "locationId", event.target.value)}><option value="">Select location</option>{inventoryLocations.map((location) => <option key={location.id} value={location.id}>{location.code} — {location.name}</option>)}</select>{!line.itemId && <input type="hidden" name="lineLocationId" value="" />}</td>
        <td><select name="lineAccountId" value={line.accountId} disabled={Boolean(line.itemId)} required={!line.itemId} onChange={(event) => update(line.id, "accountId", event.target.value)}><option value="">{line.itemId ? "Mapped from item" : "Select account"}</option>{revenueAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select>{line.itemId && <input type="hidden" name="lineAccountId" value={line.accountId} />}</td>
        <td><input name="lineQuantity" type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(event) => update(line.id, "quantity", event.target.value)} required /></td><td><input name="lineUnitPrice" type="number" min="0" step="0.01" value={line.price} onChange={(event) => update(line.id, "price", event.target.value)} required /></td>
        <td><div className="discount-entry"><select name="lineDiscountType" value={line.discountType} onChange={(event) => setLines((rows) => rows.map((entry) => entry.id === line.id ? { ...entry, discountType: event.target.value as DiscountType, discount: "0" } : entry))}><option value="NONE">None</option><option value="PERCENT">%</option><option value="AMOUNT">{currency}</option></select><input name="lineDiscountValue" type="number" min="0" max={line.discountType === "PERCENT" ? "100" : undefined} step="0.01" value={line.discount} readOnly={line.discountType === "NONE"} onChange={(event) => update(line.id, "discount", event.target.value)} required /></div></td>
        <td className="numeric">{currency} {amounts(line).net.toFixed(2)}</td><td><button type="button" className="line-delete" disabled={lines.length === 1} onClick={() => setLines((rows) => rows.filter((entry) => entry.id !== line.id))}><Trash2 size={16} /></button></td>
      </tr>)}</tbody><tfoot><tr><td colSpan={7} className="sales-table-total-label">Total sales after discount</td><td className="numeric">{currency} {sales.toFixed(2)}</td><td /></tr></tfoot></table></div>
      <div className="document-total sales-line-total"><span>Gross sales <strong>{currency} {grossSales.toFixed(2)}</strong></span><span>Discount <strong>{currency} {discountTotal.toFixed(2)}</strong></span><span className="grand-total">Sales total <strong>{currency} {sales.toFixed(2)}</strong></span></div>
    </section>
    <section className="form-section"><div className="section-heading line-heading"><div><h2>Payment tenders</h2><p>Select the actual deposit account for every cash, card, transfer, or other tender.</p></div><button type="button" className="button-secondary" onClick={() => setTenders((rows) => [...rows, { id: Math.max(...rows.map((row) => row.id)) + 1, type: "CARD", accountId: "", amount: "", reference: "" }])}><Plus size={15} />Add tender</button></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Type</th><th>Deposit account</th><th>Reference</th><th className="numeric">Amount</th><th /></tr></thead><tbody>{tenders.map((tender) => <tr key={tender.id}>
        <td><select name="tenderType" value={tender.type} onChange={(event) => setTenders((rows) => rows.map((entry) => entry.id === tender.id ? { ...entry, type: event.target.value, accountId: "" } : entry))}><option value="CASH">Cash</option><option value="CARD">Card</option><option value="BANK_TRANSFER">Bank transfer</option><option value="OTHER">Other</option></select></td>
        <td><select name="tenderAccountId" value={tender.accountId} onChange={(event) => setTenders((rows) => rows.map((entry) => entry.id === tender.id ? { ...entry, accountId: event.target.value } : entry))} required><option value="">Select account</option>{cashAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select></td>
        <td><input name="tenderReference" value={tender.reference} onChange={(event) => setTenders((rows) => rows.map((entry) => entry.id === tender.id ? { ...entry, reference: event.target.value } : entry))} /></td><td><input name="tenderAmount" type="number" min="0.01" step="0.01" value={tender.amount} onChange={(event) => setTenders((rows) => rows.map((entry) => entry.id === tender.id ? { ...entry, amount: event.target.value } : entry))} required /></td><td><button type="button" className="line-delete" disabled={tenders.length === 1} onClick={() => setTenders((rows) => rows.filter((entry) => entry.id !== tender.id))}><Trash2 size={16} /></button></td>
      </tr>)}</tbody></table></div>
    </section>
    <section className="form-section"><div className="document-total"><span>Net sales <strong>{currency} {sales.toFixed(2)}</strong></span><span>Tenders <strong>{currency} {tenderTotal.toFixed(2)}</strong></span><span className={Math.abs(tenderDifference) > .004 ? "total-warning" : "balanced-label"}>Tender difference <strong>{currency} {tenderDifference.toFixed(2)}</strong></span></div>{linesExpanded && <div className="subwindow-submit"><button type="button" className="button-secondary" onClick={() => setLinesExpanded(false)}>Cancel</button><button className="button-primary" disabled={pending || Math.abs(tenderDifference) > .004}>{pending ? "Posting…" : submitLabel}</button></div>}</section>
    </div>
    <div className="form-actions"><Link href="/cash-sales" className="button-secondary">Cancel</Link><button className="button-primary" disabled={pending || Math.abs(tenderDifference) > .004}>{pending ? "Posting…" : submitLabel}</button></div>
  </form>;
}
