"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Maximize2, Minimize2, Plus, Trash2 } from "lucide-react";
import { useActionState, useEffect, useState } from "react";
import { AutoReferenceField } from "@/components/auto-reference-field";
import { QuickInventoryItemButton, type InventoryMappingAccount } from "@/components/quick-inventory-item";
import { QuickContactButton } from "@/components/quick-contact";
type Party={id:string;code:string;name:string;paymentTermsDays:number;currencyCode:string};type Account={id:string;code:string;name:string;type:string};type Item={id:string;sku:string;name:string;revenueAccountId:string;inventoryAccountId:string};type Location={id:string;code:string;name:string};type Line={id:number;description:string;accountId:string;itemId:string;locationId:string;quantity:string;unitPrice:string;discountPercent:string};
const empty=(id:number):Line=>({id,description:"",accountId:"",itemId:"",locationId:"",quantity:"1",unitPrice:"",discountPercent:"0"});
type CommercialFormState={error?:string;redirectTo?:string};
export function CommercialForm({kind,action:submitAction,parties:initialParties,accounts,items:initialItems,locations,mappingAccounts}:{kind:"sale"|"purchase";action:(state:CommercialFormState,data:FormData)=>Promise<CommercialFormState>;parties:Party[];accounts:Account[];items:Item[];locations:Location[];mappingAccounts:InventoryMappingAccount[]}){
 const router=useRouter();
 const isSale=kind==="sale",today=new Date().toISOString().slice(0,10),[partyId,setPartyId]=useState(""),[parties,setParties]=useState(initialParties),[lines,setLines]=useState<Line[]>([empty(1)]),[items,setItems]=useState(initialItems),[quickLineId,setQuickLineId]=useState(1),[discountType,setDiscountType]=useState<"NONE"|"PERCENT"|"AMOUNT">("NONE"),[discountValue,setDiscountValue]=useState("0"),[linesExpanded,setLinesExpanded]=useState(false),currency=parties.find(p=>p.id===partyId)?.currencyCode??"BND";
 const [state,action]=useActionState(submitAction,{});
 useEffect(()=>{if(!state.redirectTo)return;router.replace(state.redirectTo);router.refresh()},[router,state.redirectTo]);
 useEffect(()=>{if(!linesExpanded)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setLinesExpanded(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[linesExpanded]);
 const amount=(l:Line)=>(Number(l.quantity)||0)*(Number(l.unitPrice)||0)*(1-(Number(l.discountPercent)||0)/100),subtotal=lines.reduce((s,l)=>s+amount(l),0),discountInput=Math.max(Number(discountValue)||0,0),discountAmount=discountType==="PERCENT"?subtotal*discountInput/100:discountType==="AMOUNT"?discountInput:0,total=Math.max(subtotal-discountAmount,0),update=(id:number,field:keyof Omit<Line,"id">,value:string)=>setLines(v=>v.map(l=>l.id===id?{...l,[field]:value}:l));
 if(state.error)return <div className="form-panel"><div className="form-error" role="alert">{state.error}</div><div className="form-actions"><button type="button" className="button-secondary" onClick={()=>window.location.reload()}>Return to invoice</button></div></div>;
 return <form action={action} className="form-panel"><section className="form-section"><div className="section-heading"><h2>{isSale?"Sales invoice":"Supplier bill"}</h2><p>Use an inventory item for stock-managed lines, or a ledger account for ordinary lines. The document date selects the accounting period automatically.</p></div><div className="form-grid">
 <div className="quick-party-field"><label>{isSale?"Customer":"Supplier"}<select name="partyId" required value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">Select party</option>{parties.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name} ({p.currencyCode})</option>)}</select></label><QuickContactButton kind={isSale?"customer":"supplier"} onCreated={party=>{setParties(current=>[...current,party]);setPartyId(party.id)}}/></div><AutoReferenceField example={isSale?"SI-2026-0001":"PI-2026-0001"}/><label>Document date<input name="documentDate" type="date" defaultValue={today} required/></label><label>Due date<input name="dueDate" type="date" defaultValue={today} required/></label><label className="span-2">Description<input name="description" required/></label></div></section>
 <section className={`form-section commercial-line-section${linesExpanded?" is-expanded":""}`}><div className="section-heading line-heading"><div><h2>Line items</h2><p>Line discounts are applied first. The document discount below is then allocated proportionally across all lines.</p></div><div className="line-heading-actions"><button type="button" className="button-secondary" onClick={()=>setLinesExpanded(value=>!value)}>{linesExpanded?<><Minimize2 size={15}/>Close sub-window</>:<><Maximize2 size={15}/>Open in sub-window</>}</button><QuickInventoryItemButton accounts={mappingAccounts} onCreated={item=>{setItems(current=>[...current,item]);setLines(current=>current.map(line=>line.id===quickLineId?{...line,itemId:item.id,accountId:isSale?item.revenueAccountId:item.inventoryAccountId,description:line.description||item.name}:line))}}/><button type="button" className="button-secondary" onClick={()=>setLines(v=>{const id=Math.max(...v.map(x=>x.id))+1;setQuickLineId(id);return[...v,empty(id)]})}><Plus size={15}/>Add line</button></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Inventory item (optional)</th><th>Location</th><th>Ledger account</th><th>Qty</th><th>Unit price</th><th>Line discount %</th><th>Net amount</th><th/></tr></thead><tbody>{lines.map(l=><tr key={l.id} onFocus={()=>setQuickLineId(l.id)}>
 <td><input name="lineDescription" value={l.description} onChange={e=>update(l.id,"description",e.target.value)} required/></td><td><select name="lineItemId" value={l.itemId} onChange={e=>{const item=items.find(x=>x.id===e.target.value);setLines(v=>v.map(x=>x.id===l.id?{...x,itemId:e.target.value,accountId:item?(isSale?item.revenueAccountId:item.inventoryAccountId):x.accountId,description:item?.name||x.description}:x))}}><option value="">Non-inventory line</option>{items.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.name}</option>)}</select></td>
 <td><select name="lineLocationId" value={l.locationId} onChange={e=>update(l.id,"locationId",e.target.value)} disabled={!l.itemId} required={!!l.itemId}><option value="">Select location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select>{!l.itemId&&<input type="hidden" name="lineLocationId" value=""/>}</td><td><select name="lineAccountId" value={l.accountId} onChange={e=>update(l.id,"accountId",e.target.value)} disabled={!!l.itemId} required={!l.itemId}><option value="">{l.itemId?"Mapped from item":"Select account"}</option>{isSale?accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>):<><optgroup label="Expense accounts">{accounts.filter(a=>a.type==="EXPENSE").map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</optgroup><optgroup label="Asset accounts">{accounts.filter(a=>a.type==="ASSET").map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</optgroup></>}</select>{l.itemId&&<input type="hidden" name="lineAccountId" value={l.accountId}/>}</td>
 <td><input name="lineQuantity" type="number" min="0.0001" step="0.0001" value={l.quantity} onChange={e=>update(l.id,"quantity",e.target.value)} required/></td><td><input name="lineUnitPrice" type="number" min="0" step="0.01" value={l.unitPrice} onChange={e=>update(l.id,"unitPrice",e.target.value)} required/></td><td><input name="lineDiscountPercent" type="number" min="0" max="100" step="0.01" value={l.discountPercent} onChange={e=>update(l.id,"discountPercent",e.target.value)} required/></td><td>{currency} {amount(l).toFixed(2)}</td><td><button type="button" className="line-delete" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div><div className="document-discount"><label>Document discount type<select name="discountType" value={discountType} onChange={event=>{const type=event.target.value as "NONE"|"PERCENT"|"AMOUNT";setDiscountType(type);setDiscountValue("0")}}><option value="NONE">No document discount</option><option value="AMOUNT">Fixed amount</option><option value="PERCENT">Percentage</option></select></label><label>{discountType==="PERCENT"?"Discount percentage":`Discount amount (${currency})`}<input name="discountValue" type="number" min="0" max={discountType==="PERCENT"?100:undefined} step="0.01" value={discountValue} onChange={event=>setDiscountValue(event.target.value)} disabled={discountType==="NONE"} required={discountType!=="NONE"}/></label></div><div className="document-total document-total-breakdown"><span>Lines <strong>{lines.length}</strong></span><span>Subtotal <strong>{currency} {subtotal.toFixed(2)}</strong></span><span>Discount <strong>− {currency} {discountAmount.toFixed(2)}</strong></span><span className="grand-total">Net amount <strong>{currency} {total.toFixed(2)}</strong></span></div></section><div className="form-actions"><Link href={isSale?"/sales":"/purchases"} className="button-secondary">Cancel</Link><button className="button-primary">Post {isSale?"invoice":"bill"}</button></div></form>
}
