"use client";
import Link from "next/link";
import { Plus, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { AutoReferenceField } from "@/components/auto-reference-field";
type Party={id:string;code:string;name:string;paymentTermsDays:number;currencyCode:string};type Account={id:string;code:string;name:string;type:string};type Item={id:string;sku:string;name:string;revenueAccountId:string;inventoryAccountId:string};type Location={id:string;code:string;name:string};type Line={id:number;description:string;accountId:string;itemId:string;locationId:string;quantity:string;unitPrice:string;discountPercent:string};
const empty=(id:number):Line=>({id,description:"",accountId:"",itemId:"",locationId:"",quantity:"1",unitPrice:"",discountPercent:"0"});
export function CommercialForm({kind,action,parties,accounts,items,locations}:{kind:"sale"|"purchase";action:(data:FormData)=>Promise<void>;parties:Party[];accounts:Account[];items:Item[];locations:Location[]}){
 const isSale=kind==="sale",today=new Date().toISOString().slice(0,10),[partyId,setPartyId]=useState(""),[lines,setLines]=useState<Line[]>([empty(1)]),currency=parties.find(p=>p.id===partyId)?.currencyCode??"BND";
 const amount=(l:Line)=>(Number(l.quantity)||0)*(Number(l.unitPrice)||0)*(1-(Number(l.discountPercent)||0)/100),total=useMemo(()=>lines.reduce((s,l)=>s+amount(l),0),[lines]),update=(id:number,field:keyof Omit<Line,"id">,value:string)=>setLines(v=>v.map(l=>l.id===id?{...l,[field]:value}:l));
 return <form action={action} className="form-panel"><section className="form-section"><div className="section-heading"><h2>{isSale?"Sales invoice":"Supplier bill"}</h2><p>Use an inventory item for stock-managed lines, or a ledger account for ordinary lines. The document date selects the accounting period automatically.</p></div><div className="form-grid">
 <label>{isSale?"Customer":"Supplier"}<select name="partyId" required value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">Select party</option>{parties.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name} ({p.currencyCode})</option>)}</select></label><AutoReferenceField example={isSale?"SI-2026-0001":"PI-2026-0001"}/><label>Document date<input name="documentDate" type="date" defaultValue={today} required/></label><label>Due date<input name="dueDate" type="date" defaultValue={today} required/></label><label className="span-2">Description<input name="description" required/></label></div></section>
 <section className="form-section"><div className="section-heading line-heading"><div><h2>Line items</h2><p>Discount is applied to each line before posting totals and inventory purchase value.</p></div><button type="button" className="button-secondary" onClick={()=>setLines(v=>[...v,empty(Math.max(...v.map(x=>x.id))+1)])}><Plus size={15}/>Add line</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Inventory item (optional)</th><th>Location</th><th>Ledger account</th><th>Qty</th><th>Unit price</th><th>Discount %</th><th>Net amount</th><th/></tr></thead><tbody>{lines.map(l=><tr key={l.id}>
 <td><input name="lineDescription" value={l.description} onChange={e=>update(l.id,"description",e.target.value)} required/></td><td><select name="lineItemId" value={l.itemId} onChange={e=>{const item=items.find(x=>x.id===e.target.value);setLines(v=>v.map(x=>x.id===l.id?{...x,itemId:e.target.value,accountId:item?(isSale?item.revenueAccountId:item.inventoryAccountId):x.accountId,description:item?.name||x.description}:x))}}><option value="">Non-inventory line</option>{items.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.name}</option>)}</select></td>
 <td><select name="lineLocationId" value={l.locationId} onChange={e=>update(l.id,"locationId",e.target.value)} disabled={!l.itemId} required={!!l.itemId}><option value="">Select location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select>{!l.itemId&&<input type="hidden" name="lineLocationId" value=""/>}</td><td><select name="lineAccountId" value={l.accountId} onChange={e=>update(l.id,"accountId",e.target.value)} disabled={!!l.itemId} required={!l.itemId}><option value="">{l.itemId?"Mapped from item":"Select account"}</option>{isSale?accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>):<><optgroup label="Expense accounts">{accounts.filter(a=>a.type==="EXPENSE").map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</optgroup><optgroup label="Asset accounts">{accounts.filter(a=>a.type==="ASSET").map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</optgroup></>}</select>{l.itemId&&<input type="hidden" name="lineAccountId" value={l.accountId}/>}</td>
 <td><input name="lineQuantity" type="number" min="0.0001" step="0.0001" value={l.quantity} onChange={e=>update(l.id,"quantity",e.target.value)} required/></td><td><input name="lineUnitPrice" type="number" min="0" step="0.01" value={l.unitPrice} onChange={e=>update(l.id,"unitPrice",e.target.value)} required/></td><td><input name="lineDiscountPercent" type="number" min="0" max="100" step="0.01" value={l.discountPercent} onChange={e=>update(l.id,"discountPercent",e.target.value)} required/></td><td>{currency} {amount(l).toFixed(2)}</td><td><button type="button" className="line-delete" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div><div className="document-total"><span>Lines <strong>{lines.length}</strong></span><span className="grand-total">Document total <strong>{currency} {total.toFixed(2)}</strong></span></div></section><div className="form-actions"><Link href={isSale?"/sales":"/purchases"} className="button-secondary">Cancel</Link><button className="button-primary">Post {isSale?"invoice":"bill"}</button></div></form>
}
