"use client";
import Link from "next/link";
import { Download, Upload } from "lucide-react";
import { useActionState, useState } from "react";
import { AutoReferenceField } from "@/components/auto-reference-field";
export type ConsumptionState={error?:string};
type Balance={itemId:string;locationId:string;sku:string;item:string;unit:string;locationCode:string;location:string;quantity:string;averageCost:string;currency:string};
export function MonthlyInventoryConsumptionForm({action,balances}:{action:(state:ConsumptionState,data:FormData)=>Promise<ConsumptionState>;balances:Balance[]}){
 const[state,formAction,pending]=useActionState(action,{}),[mode,setMode]=useState<"MANUAL"|"CSV">("MANUAL");
 return <form action={formAction} className="form-panel"><input type="hidden" name="entryMode" value={mode}/>
 <section className="form-section"><div className="section-heading"><h2>Monthly inventory consumption</h2><p>Enter the physical closing stock. Ordinora calculates consumption and weighted-average COGS without posting sales revenue again.</p></div>{state.error&&<div className="form-error" role="alert">{state.error}</div>}<div className="form-grid"><AutoReferenceField label="Reference" example="MIC-2026-0001"/><label>Count / consumption date<input name="consumptionDate" type="date" required/></label><label className="span-2">Description<input name="description" required defaultValue="Monthly inventory consumption"/></label></div><div className="form-notice"><strong>Date-based posting</strong><span>The accounting period is selected automatically from the count date. Post all purchases and transfers through this date before entering closing stock.</span></div></section>
 <section className="form-section"><div className="section-heading"><h2>Closing-stock entry method</h2><p>Use manual entry for a short list, or CSV upload for a complete stock count.</p></div><div className="segmented-control"><button type="button" className={mode==="MANUAL"?"active":""} onClick={()=>setMode("MANUAL")}>Manual entry</button><button type="button" className={mode==="CSV"?"active":""} onClick={()=>setMode("CSV")}>CSV upload</button></div>
 {mode==="MANUAL"?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Location</th><th>Unit</th><th className="numeric">Book quantity</th><th className="numeric">Average cost</th><th className="numeric">Physical closing quantity</th></tr></thead><tbody>{balances.map((row)=><tr key={`${row.itemId}-${row.locationId}`}><td><strong>{row.sku}</strong><input type="hidden" name="manualItemId" value={row.itemId}/><input type="hidden" name="manualLocationId" value={row.locationId}/></td><td>{row.item}</td><td>{row.locationCode} — {row.location}</td><td>{row.unit}</td><td className="numeric">{Number(row.quantity).toFixed(4)}</td><td className="numeric">{row.currency} {Number(row.averageCost).toFixed(4)}</td><td className="numeric"><input name="manualClosingQuantity" type="number" min="0" step="0.0001" max={row.quantity} placeholder="Enter count" aria-label={`Closing quantity for ${row.item} at ${row.location}`}/></td></tr>)}{!balances.length&&<tr><td colSpan={7}>No inventory balances are available. Enter opening inventory or purchases first.</td></tr>}</tbody></table></div>:<div><div className="form-actions"><a href="/templates/monthly-inventory-consumption.csv" download className="button-secondary"><Download size={15}/>Download template</a></div><label>Closing-stock CSV<input name="consumptionFile" type="file" accept=".csv,text/csv" required={mode==="CSV"}/></label><div className="form-notice"><strong>Required columns</strong><span>SKU, Location, ClosingQuantity. Enter the physical quantity remaining—not the quantity consumed.</span></div></div>}
 <div className="form-notice"><strong>Posting result</strong><span>Consumption = book quantity − physical closing quantity. COGS is valued at the current weighted-average cost, debiting COGS and crediting inventory.</span></div></section>
 <div className="form-actions"><Link href="/modules/inventory" className="button-secondary">Cancel</Link><button className="button-primary" disabled={pending||!balances.length}><Upload size={15}/>{pending?"Validating and posting…":"Post consumption"}</button></div></form>
}
