"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, Maximize2, Minimize2, Plus, Trash2 } from "lucide-react";
import { useActionState, useEffect, useState } from "react";
import { AutoReferenceField } from "@/components/auto-reference-field";
import { QuickInventoryItemButton, type InventoryMappingAccount } from "@/components/quick-inventory-item";
import type { DirectPaymentActionState } from "@/app/payments/actions";

type Option = { id: string; code: string; name: string };
type Item = Option & { inventoryAccountId: string };
type Line = { id: number; accountId: string; itemId: string; locationId: string; description: string; quantity: string; unitPrice: string; discount: string };
const empty = (id: number): Line => ({ id, accountId: "", itemId: "", locationId: "", description: "", quantity: "1", unitPrice: "", discount: "0" });

export function PaymentForm({ action: submitAction, bankAccounts, postingAccounts, currencies, defaultCurrency, inventoryItems: initialItems, inventoryLocations, mappingAccounts, suppliers }: { action: (state: DirectPaymentActionState, data: FormData) => Promise<DirectPaymentActionState>; bankAccounts: Option[]; postingAccounts: Option[]; currencies: string[]; defaultCurrency: string; inventoryItems: Item[]; inventoryLocations: Option[]; mappingAccounts: InventoryMappingAccount[]; suppliers: { code: string; name: string }[] }) {
  const router = useRouter();
  const [state, action, pending] = useActionState(submitAction, {});
  const [lines, setLines] = useState<Line[]>([empty(1)]), [currency, setCurrency] = useState(defaultCurrency), [paymentMethod, setPaymentMethod] = useState("BANK_TRANSFER"), [inventoryItems, setInventoryItems] = useState(initialItems), [quickLineId, setQuickLineId] = useState(1), [discountType, setDiscountType] = useState<"NONE" | "PERCENT" | "AMOUNT">("NONE"), [discountValue, setDiscountValue] = useState("0"), [linesExpanded, setLinesExpanded] = useState(false);
  useEffect(() => { if (state.redirectTo) { router.replace(state.redirectTo); router.refresh(); } }, [router, state.redirectTo]);
  const net = (line: Line) => (Number(line.quantity) || 0) * (Number(line.unitPrice) || 0) * (1 - (Number(line.discount) || 0) / 100), subtotal = lines.reduce((sum, line) => sum + net(line), 0), discountInput = Math.max(Number(discountValue) || 0, 0), discountAmount = discountType === "PERCENT" ? subtotal * discountInput / 100 : discountType === "AMOUNT" ? discountInput : 0, total = Math.max(subtotal - discountAmount, 0);
  const update = (id: number, field: keyof Omit<Line, "id">, value: string) => setLines((rows) => rows.map((line) => line.id === id ? { ...line, [field]: value } : line));
  return <form action={action} className="form-panel">
    {state.error && <div className="form-error" role="alert">{state.error}</div>}
    {state.duplicateWarning && <div className="form-notice duplicate-warning" role="alert"><AlertTriangle size={20} /><strong>Possible duplicate purchase</strong><span>{state.duplicateWarning.message}</span><input type="hidden" name="duplicateAcknowledgement" value={state.duplicateWarning.acknowledgement} /></div>}
    <section className="form-section"><div className="section-heading"><h2>Payment details</h2><p>Record expenses, assets, or inventory bought directly with cash or bank. The payment date selects the accounting period automatically.</p></div><div className="form-grid">
      <label>Payment date <em>*</em><input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><AutoReferenceField example="PAY-2026-0001" />
      <label>Paid from <em>*</em><select name="bankAccountId" required><option value="">Select cash or bank account</option>{bankAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select></label><label>Currency <em>*</em><select name="currency" value={currency} onChange={(event) => setCurrency(event.target.value)}>{currencies.map((code) => <option key={code}>{code}</option>)}</select></label>
      <label>Payee <em>*</em><input name="payee" list="direct-payment-suppliers" placeholder="Person or business paid" required /><datalist id="direct-payment-suppliers">{suppliers.map((supplier) => <option key={supplier.code} value={supplier.name}>{supplier.code}</option>)}</datalist></label><label>Description<input name="description" placeholder="Purpose of payment or receipt reference" /></label>
      <label>Payment method <em>*</em><select name="paymentMethod" value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)} required><option value="BANK_TRANSFER">Bank transfer</option><option value="BANK_CHEQUE">Bank cheque</option><option value="CASH">Cash</option><option value="OTHER">Other</option></select></label>
      {paymentMethod === "BANK_CHEQUE" && <><label>Cheque number <em>*</em><input name="chequeNumber" maxLength={60} placeholder="Enter cheque number" required /></label><label>Cheque date <em>*</em><input name="chequeDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><p className="form-help span-2">The cheque starts as Issued. Later, mark it Cleared or Returned from the Payments list.</p></>}
    </div></section>
    <section className={`form-section commercial-line-section${linesExpanded ? " is-expanded" : ""}`}><div className="section-heading line-heading"><h2>Payment allocation</h2><div className="line-heading-actions"><button type="button" className="button-secondary" onClick={() => setLinesExpanded((value) => !value)}>{linesExpanded ? <><Minimize2 size={15}/>Close sub-window</> : <><Maximize2 size={15}/>Open in sub-window</>}</button><QuickInventoryItemButton accounts={mappingAccounts} onCreated={(item) => { setInventoryItems((current) => [...current, { id: item.id, code: item.sku, name: item.name, inventoryAccountId: item.inventoryAccountId }]); setLines((rows) => rows.map((line) => line.id === quickLineId ? { ...line, itemId: item.id, accountId: item.inventoryAccountId, description: line.description || item.name } : line)); }} /><button type="button" className="button-secondary" onClick={() => setLines((rows) => { const id = Math.max(...rows.map((line) => line.id)) + 1; setQuickLineId(id); return [...rows, empty(id)]; })}><Plus size={15} />Add line</button></div></div>{linesExpanded && state.error && <div className="form-error" role="alert">{state.error}</div>}{linesExpanded && state.duplicateWarning && <div className="form-notice duplicate-warning" role="alert"><AlertTriangle size={20}/><strong>Possible duplicate purchase</strong><span>{state.duplicateWarning.message}</span></div>}
      <div className="data-table-wrap"><table className="data-table payment-allocation-table"><colgroup><col className="payment-description" /><col className="payment-item" /><col className="payment-location" /><col className="payment-account" /><col className="payment-qty" /><col className="payment-price" /><col className="payment-discount" /><col className="payment-net" /><col className="payment-action" /></colgroup><thead><tr><th>Description</th><th>Inventory item</th><th>Location</th><th>Ledger account</th><th>Qty</th><th>Unit price</th><th>Line discount %</th><th className="numeric">Net amount</th><th /></tr></thead><tbody>{lines.map((line) => <tr key={line.id} onFocus={() => setQuickLineId(line.id)}>
        <td><input name="lineDescription" value={line.description} onChange={(event) => update(line.id, "description", event.target.value)} required /></td><td><select name="lineItemId" value={line.itemId} onChange={(event) => { const item = inventoryItems.find((entry) => entry.id === event.target.value); setLines((rows) => rows.map((entry) => entry.id === line.id ? { ...entry, itemId: event.target.value, accountId: item?.inventoryAccountId ?? entry.accountId, description: item?.name || entry.description } : entry)); }}><option value="">Non-inventory payment</option>{inventoryItems.map((item) => <option value={item.id} key={item.id}>{item.code} — {item.name}</option>)}</select></td>
        <td><select name="lineLocationId" value={line.locationId} disabled={!line.itemId} required={Boolean(line.itemId)} onChange={(event) => update(line.id, "locationId", event.target.value)}><option value="">Select location</option>{inventoryLocations.map((location) => <option value={location.id} key={location.id}>{location.code} — {location.name}</option>)}</select>{!line.itemId && <input type="hidden" name="lineLocationId" value="" />}</td><td><select name="lineAccountId" value={line.accountId} disabled={Boolean(line.itemId)} required={!line.itemId} onChange={(event) => update(line.id, "accountId", event.target.value)}><option value="">{line.itemId ? "Mapped from item" : "Select posting account"}</option>{postingAccounts.map((account) => <option value={account.id} key={account.id}>{account.code} — {account.name}</option>)}</select>{line.itemId && <input type="hidden" name="lineAccountId" value={line.accountId} />}</td>
        <td><input name="lineQuantity" type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(event) => update(line.id, "quantity", event.target.value)} required /></td><td><input name="lineUnitPrice" type="number" min="0" step="0.01" value={line.unitPrice} onChange={(event) => update(line.id, "unitPrice", event.target.value)} required /></td><td><input name="lineDiscountPercent" type="number" min="0" max="100" step="0.01" value={line.discount} onChange={(event) => update(line.id, "discount", event.target.value)} required /></td><td className="numeric">{currency} {net(line).toFixed(2)}</td><td><button type="button" className="line-delete" disabled={lines.length === 1} onClick={() => setLines((rows) => rows.filter((entry) => entry.id !== line.id))}><Trash2 size={16} /></button></td>
      </tr>)}</tbody></table></div><div className="document-discount"><label>Payment discount type<select name="discountType" value={discountType} onChange={(event) => { const type = event.target.value as "NONE" | "PERCENT" | "AMOUNT"; setDiscountType(type); setDiscountValue("0"); }}><option value="NONE">No payment discount</option><option value="AMOUNT">Fixed amount</option><option value="PERCENT">Percentage</option></select></label><label>{discountType === "PERCENT" ? "Discount percentage" : `Discount amount (${currency})`}<input name="discountValue" type="number" min="0" max={discountType === "PERCENT" ? 100 : undefined} step="0.01" value={discountValue} onChange={(event) => setDiscountValue(event.target.value)} disabled={discountType === "NONE"} required={discountType !== "NONE"}/></label></div><div className="document-total document-total-breakdown"><span>Lines <strong>{lines.length}</strong></span><span>Subtotal <strong>{currency} {subtotal.toFixed(2)}</strong></span><span>Discount <strong>− {currency} {discountAmount.toFixed(2)}</strong></span><span className="grand-total">Net amount <strong>{currency} {total.toFixed(2)}</strong></span></div>{linesExpanded && <div className="subwindow-submit"><button type="button" className="button-secondary" onClick={() => setLinesExpanded(false)}>Cancel</button><button className="button-primary" disabled={pending}>{pending ? "Posting…" : state.duplicateWarning ? "Post as separate purchase" : "Post payment"}</button></div>}
    </section><div className="form-actions"><Link href="/payments" className="button-secondary">Cancel</Link><button className="button-primary" disabled={pending}>{pending ? "Checking…" : state.duplicateWarning ? "Post as separate purchase" : "Post payment"}</button></div>
  </form>;
}
