"use client";
import Link from "next/link";
import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { AutoReferenceField } from "@/components/auto-reference-field";

type Option = { id: string; code: string; name: string };
type Item = Option & { inventoryAccountId: string };
type Line = { id: number; accountId: string; itemId: string; locationId: string; description: string; quantity: string; unitPrice: string; discount: string };
const empty = (id: number): Line => ({ id, accountId: "", itemId: "", locationId: "", description: "", quantity: "1", unitPrice: "", discount: "0" });

export function PaymentForm({ action, bankAccounts, postingAccounts, currencies, defaultCurrency, inventoryItems, inventoryLocations }: { action: (data: FormData) => Promise<void>; bankAccounts: Option[]; postingAccounts: Option[]; currencies: string[]; defaultCurrency: string; inventoryItems: Item[]; inventoryLocations: Option[] }) {
  const [lines, setLines] = useState<Line[]>([empty(1)]), [currency, setCurrency] = useState(defaultCurrency);
  const net = (line: Line) => (Number(line.quantity) || 0) * (Number(line.unitPrice) || 0) * (1 - (Number(line.discount) || 0) / 100), total = lines.reduce((sum, line) => sum + net(line), 0);
  const update = (id: number, field: keyof Omit<Line, "id">, value: string) => setLines((rows) => rows.map((line) => line.id === id ? { ...line, [field]: value } : line));
  return <form action={action} className="form-panel">
    <section className="form-section"><div className="section-heading"><h2>Payment details</h2><p>Record expenses, assets, or inventory bought directly with cash or bank. The payment date selects the accounting period automatically.</p></div><div className="form-grid">
      <label>Payment date <em>*</em><input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><AutoReferenceField example="PAY-2026-0001" />
      <label>Paid from <em>*</em><select name="bankAccountId" required><option value="">Select cash or bank account</option>{bankAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select></label><label>Currency <em>*</em><select name="currency" value={currency} onChange={(event) => setCurrency(event.target.value)}>{currencies.map((code) => <option key={code}>{code}</option>)}</select></label>
      <label>Payee <em>*</em><input name="payee" placeholder="Person or business paid" required /></label><label>Description<input name="description" placeholder="Purpose of payment or receipt reference" /></label>
    </div></section>
    <section className="form-section"><div className="section-heading line-heading"><div><h2>Payment allocation</h2><p>Discount reduces the amount paid and the inventory acquisition cost.</p></div><button type="button" className="button-secondary" onClick={() => setLines((rows) => [...rows, empty(Math.max(...rows.map((line) => line.id)) + 1)])}><Plus size={15} />Add line</button></div>
      <div className="data-table-wrap"><table className="data-table payment-allocation-table"><colgroup><col className="payment-description" /><col className="payment-item" /><col className="payment-location" /><col className="payment-account" /><col className="payment-qty" /><col className="payment-price" /><col className="payment-discount" /><col className="payment-net" /><col className="payment-action" /></colgroup><thead><tr><th>Description</th><th>Inventory item</th><th>Location</th><th>Ledger account</th><th>Qty</th><th>Unit price</th><th>Discount %</th><th className="numeric">Net amount</th><th /></tr></thead><tbody>{lines.map((line) => <tr key={line.id}>
        <td><input name="lineDescription" value={line.description} onChange={(event) => update(line.id, "description", event.target.value)} required /></td><td><select name="lineItemId" value={line.itemId} onChange={(event) => { const item = inventoryItems.find((entry) => entry.id === event.target.value); setLines((rows) => rows.map((entry) => entry.id === line.id ? { ...entry, itemId: event.target.value, accountId: item?.inventoryAccountId ?? entry.accountId, description: item?.name || entry.description } : entry)); }}><option value="">Non-inventory payment</option>{inventoryItems.map((item) => <option value={item.id} key={item.id}>{item.code} — {item.name}</option>)}</select></td>
        <td><select name="lineLocationId" value={line.locationId} disabled={!line.itemId} required={Boolean(line.itemId)} onChange={(event) => update(line.id, "locationId", event.target.value)}><option value="">Select location</option>{inventoryLocations.map((location) => <option value={location.id} key={location.id}>{location.code} — {location.name}</option>)}</select>{!line.itemId && <input type="hidden" name="lineLocationId" value="" />}</td><td><select name="lineAccountId" value={line.accountId} disabled={Boolean(line.itemId)} required={!line.itemId} onChange={(event) => update(line.id, "accountId", event.target.value)}><option value="">{line.itemId ? "Mapped from item" : "Select posting account"}</option>{postingAccounts.map((account) => <option value={account.id} key={account.id}>{account.code} — {account.name}</option>)}</select>{line.itemId && <input type="hidden" name="lineAccountId" value={line.accountId} />}</td>
        <td><input name="lineQuantity" type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(event) => update(line.id, "quantity", event.target.value)} required /></td><td><input name="lineUnitPrice" type="number" min="0" step="0.01" value={line.unitPrice} onChange={(event) => update(line.id, "unitPrice", event.target.value)} required /></td><td><input name="lineDiscountPercent" type="number" min="0" max="100" step="0.01" value={line.discount} onChange={(event) => update(line.id, "discount", event.target.value)} required /></td><td className="numeric">{currency} {net(line).toFixed(2)}</td><td><button type="button" className="line-delete" disabled={lines.length === 1} onClick={() => setLines((rows) => rows.filter((entry) => entry.id !== line.id))}><Trash2 size={16} /></button></td>
      </tr>)}</tbody></table></div><div className="document-total"><span>Lines <strong>{lines.length}</strong></span><span className="grand-total">Payment total <strong>{currency} {total.toFixed(2)}</strong></span></div>
    </section><div className="form-actions"><Link href="/payments" className="button-secondary">Cancel</Link><button className="button-primary">Post payment</button></div>
  </form>;
}
