"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{z}from"zod";import{db}from"@/lib/db";import{requireActiveTenant}from"@/lib/session";
const roles=["SYSTEM_ADMIN","FIRM_ADMIN","ACCOUNTANT","REVIEWER"];
async function context(){const value=await requireActiveTenant();if(!value.user.staffRole||!roles.includes(value.user.staffRole))throw new Error("Your role cannot update capital-allowance working papers.");return value}
const optionalDate=z.preprocess(v=>v===""?undefined:v,z.coerce.date().optional());
const schema=z.object({taxYearId:z.string().min(1),assetCode:z.string().trim().min(1).max(40),description:z.string().trim().min(2).max(180),category:z.string().trim().min(2).max(80),acquiredOn:optionalDate,originalCost:z.coerce.number().min(0),qualifyingAddition:z.coerce.number().min(0),taxWrittenDownValueBf:z.coerce.number().min(0),disposalDeduction:z.coerce.number().min(0),initialAllowanceRate:z.coerce.number().min(0).max(100),annualAllowanceRate:z.coerce.number().min(0).max(100),privateUsePercent:z.coerce.number().min(0).max(100),status:z.enum(["ACTIVE","DISPOSED","EXCLUDED"]),notes:z.string().trim().max(1000).optional()});
function values(i:z.infer<typeof schema>){return{...i,acquiredOn:i.acquiredOn??null,notes:i.notes||null}}
export async function createCapitalAllowanceItem(formData:FormData){const{user,active}=await context(),parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect(`/tax/capital-allowances?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Enter valid asset details.")}`);const i=parsed.data,year=await db.taxYear.findFirst({where:{id:i.taxYearId,tenantId:active.id}});if(!year)redirect("/tax/capital-allowances?error=Select+a+valid+tax+year.");if(await db.capitalAllowanceItem.count({where:{tenantId:active.id,taxYearId:i.taxYearId,assetCode:i.assetCode}}))redirect(`/tax/capital-allowances?year=${i.taxYearId}&error=${encodeURIComponent(`Asset code ${i.assetCode} already exists in this tax year.`)}`);await db.$transaction(async tx=>{const row=await tx.capitalAllowanceItem.create({data:{tenantId:active.id,...values(i)}});await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"CAPITAL_ALLOWANCE_ITEM_CREATED",entityType:"CapitalAllowanceItem",entityId:row.id,newValues:{taxYearId:i.taxYearId,assetCode:i.assetCode,description:i.description}}})});redirect(`/tax/capital-allowances?year=${i.taxYearId}`)}
export async function updateCapitalAllowanceItem(id:string,formData:FormData){const{user,active}=await context(),parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect(`/tax/capital-allowances/${id}/edit?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Enter valid asset details.")}`);const i=parsed.data,previous=await db.capitalAllowanceItem.findFirst({where:{id,tenantId:active.id}});if(!previous)throw new Error("Capital-allowance item not found.");if(await db.capitalAllowanceItem.count({where:{tenantId:active.id,taxYearId:i.taxYearId,assetCode:i.assetCode,id:{not:id}}}))redirect(`/tax/capital-allowances/${id}/edit?error=${encodeURIComponent(`Asset code ${i.assetCode} already exists in this tax year.`)}`);await db.$transaction([db.capitalAllowanceItem.update({where:{id},data:values(i)}),db.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"CAPITAL_ALLOWANCE_ITEM_UPDATED",entityType:"CapitalAllowanceItem",entityId:id,previousValues:{assetCode:previous.assetCode,description:previous.description,status:previous.status},newValues:{assetCode:i.assetCode,description:i.description,status:i.status}}})]);redirect(`/tax/capital-allowances?year=${i.taxYearId}`)}
export async function deleteCapitalAllowanceItem(id:string,formData:FormData){const{user,active}=await context(),reason=z.string().trim().min(5).max(240).parse(formData.get("reason"));z.literal("DELETE").parse(formData.get("confirmation"));const row=await db.capitalAllowanceItem.findFirst({where:{id,tenantId:active.id}});if(!row)throw new Error("Capital-allowance item not found.");await db.$transaction(async tx=>{await tx.auditEvent.create({data:{firmId:user.firmId,tenantId:active.id,actorId:user.id,actorKind:"STAFF",action:"CAPITAL_ALLOWANCE_ITEM_DELETED",entityType:"CapitalAllowanceItem",entityId:id,previousValues:{assetCode:row.assetCode,description:row.description,taxYearId:row.taxYearId},reason}});await tx.capitalAllowanceItem.delete({where:{id}})});revalidatePath("/tax/capital-allowances");redirect(`/tax/capital-allowances?year=${row.taxYearId}`)}
