import Link from "next/link";
import { notFound } from "next/navigation";
import { Prisma } from "@prisma/client";
import { agedPayables,agedReceivables,ledgerBalances } from "@/lib/reports";
import { requireClientFinancialAccess } from "@/lib/session";

export const dynamic="force-dynamic";
const zero=new Prisma.Decimal(0),money=(currency:string,value:Prisma.Decimal.Value)=>`${currency} ${Number(value).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`,names:Record<string,string>={cash:"Cash & bank",revenue:"Revenue",receivables:"Accounts receivable",payables:"Accounts payable",profit:"Net profit"};

export default async function LiveDrilldownPage({params}:{params:Promise<{metric:string}>}){const{metric}=await params,user=await requireClientFinancialAccess(),tenant=user.tenant!;if(tenant.reportMode!=="LIVE_POSTED_AND_PUBLISHED"||!tenant.enabledDashboardCards.includes(metric)||!names[metric])notFound();const asOf=new Date();let heads:string[]=[],rows:string[][]=[];if(metric==="receivables"||metric==="payables"){const balances=metric==="receivables"?await agedReceivables(tenant.id,asOf):await agedPayables(tenant.id,asOf);heads=["Reference",metric==="receivables"?"Customer":"Supplier","Due date","Age","Outstanding"];rows=balances.map(row=>[row.reference,row.party,row.due.toLocaleDateString("en-BN"),row.bucket,money(tenant.defaultCurrency,row.outstanding)])}else{const balances=await ledgerBalances(tenant.id,undefined,asOf),filtered=metric==="cash"?balances.filter(row=>row.type==="ASSET"&&row.classification==="Cash and cash equivalents"):metric==="revenue"?balances.filter(row=>row.type==="REVENUE"):balances.filter(row=>row.type==="REVENUE"||row.type==="EXPENSE");heads=["Code","Account","Classification","Amount"];rows=filtered.map(row=>{const value=row.type==="REVENUE"?row.credit.sub(row.debit):row.debit.sub(row.credit);return[row.code,row.name,row.classification,money(tenant.defaultCurrency,value)]});if(metric==="profit"){const revenue=filtered.filter(row=>row.type==="REVENUE").reduce((sum,row)=>sum.add(row.credit.sub(row.debit)),zero),expenses=filtered.filter(row=>row.type==="EXPENSE").reduce((sum,row)=>sum.add(row.debit.sub(row.credit)),zero);rows.push(["","Net profit / (loss)","Accrual accounting · revenue less expenses",money(tenant.defaultCurrency,revenue.sub(expenses))])}}return <main className="portal-page"><header className="portal-header"><div><strong>Ordinora</strong><span>Client Portal</span></div><Link href="/portal" className="button-secondary">Back to dashboard</Link></header><section className="portal-content"><header className="module-header"><div><p className="eyebrow">LIVE POSTED REPORT</p><h2>{names[metric]}</h2><p>As at {asOf.toLocaleString("en-BN")} · {metric==="profit"?"Accrual accounting · ":""}posted entries only</p></div></header><div className="form-notice"><span>This live view can change when your accountant posts or corrects transactions. Published reports remain fixed versions.</span></div><section className="surface-card table-card"><div className="data-table-wrap"><table className="data-table"><thead><tr>{heads.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex} className={cellIndex===row.length-1?"numeric":""}>{cell}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={heads.length} className="table-empty">No posted balances are available.</td></tr>}</tbody></table></div></section></section></main>}
