import Link from "next/link";
import { Save } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AutoReferenceField } from "@/components/auto-reference-field";
import { db } from "@/lib/db";
import { requireActiveTenant } from "@/lib/session";
import { createJournal } from "../actions";
export const dynamic="force-dynamic";
export default async function NewJournalPage(){const{user,tenants,active}=await requireActiveTenant();const accounts=await db.account.findMany({where:{tenantId:active.id,isActive:true},orderBy:{code:"asc"}});return <AppShell user={{displayName:user.displayName,email:user.email,role:user.staffRole?.replaceAll("_"," ")??"STAFF",firmName:user.firm.name}} tenants={tenants} activeTenant={active} pageTitle="New Journal Entry" pageDescription="Create a balanced posting; the accounting date selects the open period"><main className="module-page form-page"><div className="form-notice"><strong>Direct posting</strong><span>This journal posts immediately after validation. Posted entries are corrected by reversal, not editing.</span></div><form action={createJournal} className="form-panel"><section className="form-section"><div className="section-heading"><h2>Journal details</h2><p>Reference, date and posting context.</p></div><div className="form-grid"><AutoReferenceField example="MJ-2026-0001"/><label>Accounting date <em>*</em><input name="accountingDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="span-2">Description <em>*</em><input name="description" required maxLength={240} placeholder="Describe the purpose of this journal"/></label></div></section><section className="form-section"><div className="section-heading"><h2>Posting lines</h2><p>Total debits and credits must be equal.</p></div><div className="posting-grid"><label>Debit account <em>*</em><select name="debitAccountId" required><option value="">Select account</option>{accounts.map((a)=><option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Credit account <em>*</em><select name="creditAccountId" required><option value="">Select account</option>{accounts.map((a)=><option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Amount (BND) <em>*</em><input name="amount" inputMode="decimal" required pattern="\d+(\.\d{1,2})?" placeholder="0.00"/></label></div><div className="balance-preview"><span>Debit total <strong>B$0.00</strong></span><span>Credit total <strong>B$0.00</strong></span><span className="balanced-label">Validation runs before posting</span></div></section><div className="form-actions"><Link href="/journals" className="button-secondary">Cancel</Link><button className="button-primary"><Save size={16}/>Post journal</button></div></form><button className="floating-save" type="submit" form="journal-form" aria-label="Post journal"><Save size={17}/>Post journal</button></main></AppShell>}

