ALTER TABLE "SalesInvoiceLine" ADD COLUMN "discountPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;

ALTER TABLE "SupplierBillLine" ADD COLUMN "discountPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;

ALTER TABLE "PaymentLine" ADD COLUMN "discountPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;

ALTER TABLE "DailyCashSaleLine" ADD COLUMN "discountPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;
